services:
  - type: web
    name: chaitanya-college-website
    env: python
    plan: free
    buildCommand: "./build.sh"
    startCommand: "gunicorn chaitanya_site.wsgi:application"
    envVars:
      - key: DEBUG
        value: False
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4

databases:
  - name: chaitanya-college-db
    plan: free
