# Generated by Django 5.0.7 on 2025-08-24 02:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('campus', 'Campus'), ('events', 'Events'), ('cultural', 'Cultural'), ('sports', 'Sports'), ('academic', 'Academic'), ('facilities', 'Facilities'), ('achievements', 'Achievements')], default='campus', max_length=20)),
                ('cover_image', models.ImageField(blank=True, upload_to='gallery/covers/')),
                ('is_featured', models.BooleanField(default=False, help_text='Show on homepage')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.IntegerField(default=0)),
                ('meta_description', models.TextField(blank=True, max_length=160)),
            ],
            options={
                'verbose_name_plural': 'Galleries',
                'ordering': ['ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='HeaderInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(default='chaitanyapamgarh@gmail.com', max_length=254)),
                ('phone', models.CharField(default='+91-9425540666', max_length=20)),
                ('address', models.CharField(default='Pamgarh, Janjgir Champa, Chhattisgarh', max_length=200)),
                ('facebook_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('instagram_url', models.URLField(blank=True)),
                ('twitter_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('show_social_links', models.BooleanField(default=True)),
                ('show_contact_info', models.BooleanField(default=True)),
                ('header_background_color', models.CharField(default='#1f2937', help_text='Hex color code', max_length=7)),
                ('header_text_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Header Information',
                'verbose_name_plural': 'Header Information',
            },
        ),
        migrations.CreateModel(
            name='NavbarInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand_name', models.CharField(default='Chaitanya Science and Arts College', max_length=200)),
                ('brand_subtitle', models.CharField(blank=True, default='Shaheed Nandkumar Patel Vishwavidyalaya, Raigarh', max_length=300)),
                ('logo', models.ImageField(blank=True, upload_to='navbar/')),
                ('show_logo', models.BooleanField(default=True)),
                ('show_brand_text', models.BooleanField(default=True)),
                ('navbar_background_color', models.CharField(default='#ffffff', help_text='Hex color code', max_length=7)),
                ('navbar_text_color', models.CharField(default='#374151', help_text='Hex color code', max_length=7)),
                ('navbar_hover_color', models.CharField(default='#dc2626', help_text='Hex color code', max_length=7)),
                ('navbar_border_color', models.CharField(default='#e5e7eb', help_text='Hex color code', max_length=7)),
                ('enable_search', models.BooleanField(default=True)),
                ('search_placeholder', models.CharField(blank=True, default='Search...', max_length=100)),
                ('is_sticky', models.BooleanField(default=False, help_text='Make navbar stick to top when scrolling')),
                ('show_below_header', models.BooleanField(default=True, help_text='Position navbar below header/top bar')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Navbar Configuration',
                'verbose_name_plural': 'Navbar Configuration',
            },
        ),
        migrations.AlterField(
            model_name='blockform',
            name='form_type',
            field=models.CharField(choices=[('contact', 'Contact Form'), ('registration', 'Registration Form'), ('feedback', 'Feedback Form')], default='contact', max_length=20),
        ),
        migrations.CreateModel(
            name='GalleryPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='gallery/photos/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('caption', models.TextField(blank=True)),
                ('photographer', models.CharField(blank=True, max_length=100)),
                ('date_taken', models.DateField(blank=True, null=True)),
                ('ordering', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('gallery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='college_website.gallery')),
            ],
            options={
                'ordering': ['ordering', '-created_at'],
            },
        ),
    ]
