# Generated by Django 5.0.7 on 2025-08-24 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0003_gallery_galleryphoto'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='galleryphoto',
            options={'ordering': ['ordering', 'created_at'], 'verbose_name': 'Gallery Photo', 'verbose_name_plural': 'Gallery Photos'},
        ),
        migrations.AddField(
            model_name='galleryphoto',
            name='category',
            field=models.CharField(choices=[('events', 'Events'), ('activities', 'Activities'), ('campus', 'Campus Life'), ('academics', 'Academics'), ('sports', 'Sports'), ('cultural', 'Cultural'), ('general', 'General')], default='general', max_length=20),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='ordering',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
