# Generated by Django 5.0.7 on 2025-08-24 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0004_alter_galleryphoto_options_galleryphoto_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='galleryphoto',
            name='alt_text',
            field=models.CharField(blank=True, help_text='Alternative text for screen readers', max_length=255),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='caption',
            field=models.TextField(blank=True, help_text='Descriptive caption for accessibility and SEO'),
        ),
        migrations.AlterField(
            model_name='galleryphoto',
            name='title',
            field=models.CharField(blank=True, help_text='SEO-friendly title for the image', max_length=200),
        ),
    ]
