# Generated by Django 5.0.7 on 2025-08-24 15:16

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0006_admissioninfo_alumniprofile_elearningcourse_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScrollingNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Brief notification title', max_length=200)),
                ('message', models.TextField(help_text='Detailed notification message')),
                ('link_text', models.CharField(blank=True, help_text="Optional link text (e.g., 'Read More', 'Apply Now')", max_length=50)),
                ('link_url', models.URLField(blank=True, help_text='Optional link URL')),
                ('priority', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High'), ('urgent', 'Urgent')], default='medium', max_length=10)),
                ('color_theme', models.CharField(choices=[('primary', 'Primary Blue'), ('success', 'Success Green'), ('warning', 'Warning Yellow'), ('danger', 'Danger Red'), ('info', 'Info Cyan'), ('dark', 'Dark')], default='primary', max_length=10)),
                ('show_icon', models.BooleanField(default=True)),
                ('icon_class', models.CharField(default='fas fa-bullhorn', help_text='FontAwesome icon class', max_length=50)),
                ('start_date', models.DateTimeField(help_text='When to start showing this notification')),
                ('end_date', models.DateTimeField(blank=True, help_text='When to stop showing (leave empty for permanent)', null=True)),
                ('scroll_speed', models.IntegerField(default=50, help_text='Scroll speed in seconds for full cycle')),
                ('pause_on_hover', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.IntegerField(default=0, help_text='Lower numbers appear first')),
            ],
            options={
                'verbose_name': 'Scrolling Notification',
                'verbose_name_plural': 'Scrolling Notifications',
                'ordering': ['display_order', '-priority', '-created_at'],
            },
        ),
        migrations.RemoveField(
            model_name='examresult',
            name='instructions',
        ),
        migrations.AlterField(
            model_name='examresult',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True),
        ),
    ]
