# Generated by Django 5.0.7 on 2025-08-25 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0007_scrollingnotification_remove_examresult_instructions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SliderImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Caption title that appears on the slide', max_length=200)),
                ('caption', models.TextField(blank=True, help_text='Optional description text that appears below the title')),
                ('image', models.ImageField(help_text='Slider image (recommended size: 1920x800px or 16:9 ratio)', upload_to='slider/')),
                ('button_text', models.CharField(blank=True, help_text="Optional button text (e.g., 'Learn More', 'Apply Now')", max_length=50)),
                ('button_url', models.URLField(blank=True, help_text='Optional button link URL')),
                ('ordering', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('is_active', models.BooleanField(default=True, help_text='Uncheck to hide this slide from the slider')),
                ('start_date', models.DateTimeField(blank=True, help_text='Optional: When to start showing this slide (leave empty for immediate)', null=True)),
                ('end_date', models.DateTimeField(blank=True, help_text='Optional: When to stop showing this slide (leave empty for permanent)', null=True)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility (auto-generated from title if empty)', max_length=200)),
            ],
            options={
                'verbose_name': 'Slider Image',
                'verbose_name_plural': 'Slider Images',
                'ordering': ['ordering', '-created_at'],
            },
        ),
    ]
