# Generated by Django 5.0.7 on 2025-08-25 16:06

import django_ckeditor_5.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0008_sliderimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Mr. Veerendra Tiwari', max_length=100)),
                ('designation', models.CharField(default='Director', max_length=100)),
                ('qualifications', models.CharField(blank=True, help_text='Educational qualifications and certifications', max_length=300)),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Years of experience in education sector', null=True)),
                ('message_title', models.CharField(default="Director's Message", help_text='Title for the message section', max_length=200)),
                ('message_content', django_ckeditor_5.fields.CKEditor5Field(help_text="Director's message to students and visitors")),
                ('vision', models.TextField(blank=True, help_text="Director's vision for the institution")),
                ('achievements', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Notable achievements and awards')),
                ('profile_photo', models.ImageField(blank=True, help_text="Director's profile photo (recommended size: 400x500px)", upload_to='leadership/director/')),
                ('email', models.EmailField(blank=True, help_text='Official email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter Profile')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook Profile')),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Display message snippet on homepage')),
                ('show_achievements', models.BooleanField(default=True, help_text='Display achievements section')),
                ('show_contact_info', models.BooleanField(default=True, help_text='Display contact information')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable director message section')),
                ('meta_description', models.CharField(blank=True, help_text="SEO meta description for director's message page", max_length=160)),
            ],
            options={
                'verbose_name': "Director's Message",
                'verbose_name_plural': "Director's Messages",
            },
        ),
        migrations.CreateModel(
            name='PrincipalMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Dr. Vinod Kumar Gupta', max_length=100)),
                ('designation', models.CharField(default='Principal', max_length=100)),
                ('qualifications', models.CharField(blank=True, help_text='Educational qualifications and certifications', max_length=300)),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization or expertise', max_length=200)),
                ('experience_years', models.PositiveIntegerField(blank=True, help_text='Years of experience in education sector', null=True)),
                ('message_title', models.CharField(default="Principal's Message", help_text='Title for the message section', max_length=200)),
                ('message_content', django_ckeditor_5.fields.CKEditor5Field(help_text="Principal's message to students and visitors")),
                ('educational_philosophy', models.TextField(blank=True, help_text="Principal's educational philosophy and approach")),
                ('achievements', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Notable achievements, publications, and awards')),
                ('profile_photo', models.ImageField(blank=True, help_text="Principal's profile photo (recommended size: 400x500px)", upload_to='leadership/principal/')),
                ('email', models.EmailField(blank=True, help_text='Official email address', max_length=254)),
                ('phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('office_hours', models.CharField(blank=True, help_text='Office hours for student meetings', max_length=100)),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn Profile')),
                ('researchgate_url', models.URLField(blank=True, verbose_name='ResearchGate Profile')),
                ('orcid_url', models.URLField(blank=True, verbose_name='ORCID Profile')),
                ('twitter_url', models.URLField(blank=True, verbose_name='Twitter Profile')),
                ('show_on_homepage', models.BooleanField(default=True, help_text='Display message snippet on homepage')),
                ('show_achievements', models.BooleanField(default=True, help_text='Display achievements section')),
                ('show_contact_info', models.BooleanField(default=True, help_text='Display contact information')),
                ('show_office_hours', models.BooleanField(default=True, help_text='Display office hours information')),
                ('is_active', models.BooleanField(default=True, help_text='Enable/disable principal message section')),
                ('meta_description', models.CharField(blank=True, help_text="SEO meta description for principal's message page", max_length=160)),
            ],
            options={
                'verbose_name': "Principal's Message",
                'verbose_name_plural': "Principal's Messages",
            },
        ),
        migrations.AddField(
            model_name='event',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show on homepage'),
        ),
        migrations.AddField(
            model_name='event',
            name='organizer',
            field=models.CharField(blank=True, help_text='Event organizer or department', max_length=200),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_link',
            field=models.URLField(blank=True, help_text='External registration form URL'),
        ),
        migrations.AddField(
            model_name='event',
            name='registration_required',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='EventImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(help_text='Event image (recommended size: 800x600px or larger)', upload_to='events/gallery/')),
                ('caption', models.CharField(blank=True, help_text='Optional image caption', max_length=200)),
                ('alt_text', models.CharField(blank=True, help_text='Alternative text for accessibility', max_length=200)),
                ('is_cover', models.BooleanField(default=False, help_text='Use as main cover image for this event')),
                ('ordering', models.IntegerField(default=0, help_text='Display order (lower numbers appear first)')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='college_website.event')),
            ],
            options={
                'verbose_name': 'Event Image',
                'verbose_name_plural': 'Event Images',
                'ordering': ['ordering', '-created_at'],
            },
        ),
    ]
