# Generated by Django 5.0.7 on 2025-08-25 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0009_directormessage_principalmessage_event_contact_email_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='headerinfo',
            name='address',
        ),
        migrations.RemoveField(
            model_name='headerinfo',
            name='header_text_color',
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='address_color',
            field=models.CharField(default='#6b7280', help_text='Hex color code for address', max_length=7),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='address_font_size',
            field=models.IntegerField(default=14, help_text='Font size in pixels (10-24)'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='address_font_weight',
            field=models.CharField(choices=[('300', 'Light'), ('400', 'Normal'), ('500', 'Medium'), ('600', 'Semi-bold')], default='400', max_length=20),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='affiliations_color',
            field=models.CharField(default='#059669', help_text='Hex color code for affiliations', max_length=7),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='affiliations_font_size',
            field=models.IntegerField(default=12, help_text='Font size in pixels (10-20)'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='affiliations_font_weight',
            field=models.CharField(choices=[('300', 'Light'), ('400', 'Normal'), ('500', 'Medium'), ('600', 'Semi-bold')], default='500', max_length=20),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='college_address',
            field=models.TextField(default='Pamgarh, Janjgir Champa, Chhattisgarh, India - 495554', help_text='Complete college address'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='college_affiliations',
            field=models.TextField(default='Affiliated to Shaheed Nandkumar Patel Vishwavidyalaya, Raigarh\nRecognized by UGC | NAAC Grade A+ | IIC 3 Star Rating', help_text='College affiliations and recognitions (use line breaks for multiple lines)'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='college_name',
            field=models.CharField(default='Chaitanya Science and Arts College', help_text='Full college name', max_length=300),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='college_name_color',
            field=models.CharField(default='#1f2937', help_text='Hex color code for college name', max_length=7),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='college_name_font_family',
            field=models.CharField(choices=[('Arial, sans-serif', 'Arial'), ('Georgia, serif', 'Georgia'), ('Times New Roman, serif', 'Times New Roman'), ('Helvetica, sans-serif', 'Helvetica'), ('Verdana, sans-serif', 'Verdana'), ('Roboto, sans-serif', 'Roboto'), ('Open Sans, sans-serif', 'Open Sans'), ('Lato, sans-serif', 'Lato'), ('Poppins, sans-serif', 'Poppins'), ('Montserrat, sans-serif', 'Montserrat')], default='Poppins, sans-serif', max_length=50),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='college_name_font_size',
            field=models.IntegerField(default=28, help_text='Font size in pixels (12-48)'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='college_name_font_weight',
            field=models.CharField(choices=[('300', 'Light'), ('400', 'Normal'), ('500', 'Medium'), ('600', 'Semi-bold'), ('700', 'Bold'), ('800', 'Extra-bold')], default='700', max_length=20),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='contact_color',
            field=models.CharField(default='#374151', help_text='Hex color code for contact info', max_length=7),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='contact_font_size',
            field=models.IntegerField(default=13, help_text='Font size for contact info (10-18)'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='enable_animations',
            field=models.BooleanField(default=True, help_text='Enable hover animations and transitions'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='header_border_bottom',
            field=models.BooleanField(default=True, help_text='Show bottom border'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='header_border_color',
            field=models.CharField(default='#e5e7eb', help_text='Border color (hex code)', max_length=7),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='header_layout',
            field=models.CharField(choices=[('centered', 'Centered'), ('left_right', 'Left-Right Split'), ('three_column', 'Three Column')], default='three_column', help_text='Choose header layout style', max_length=20),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='header_shadow',
            field=models.BooleanField(default=True, help_text='Add shadow effect to header'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='hide_affiliations_mobile',
            field=models.BooleanField(default=False, help_text='Hide affiliations on mobile devices'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='left_logo_1',
            field=models.ImageField(blank=True, help_text='First left logo (recommended: 60x60px)', upload_to='header/logos/left/'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='left_logo_1_alt',
            field=models.CharField(blank=True, help_text='Alt text for logo 1', max_length=100),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='left_logo_1_link',
            field=models.URLField(blank=True, help_text='Optional link for logo 1'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='left_logo_2',
            field=models.ImageField(blank=True, help_text='Second left logo (recommended: 60x60px)', upload_to='header/logos/left/'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='left_logo_2_alt',
            field=models.CharField(blank=True, help_text='Alt text for logo 2', max_length=100),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='left_logo_2_link',
            field=models.URLField(blank=True, help_text='Optional link for logo 2'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='left_logo_3',
            field=models.ImageField(blank=True, help_text='Third left logo (recommended: 60x60px)', upload_to='header/logos/left/'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='left_logo_3_alt',
            field=models.CharField(blank=True, help_text='Alt text for logo 3', max_length=100),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='left_logo_3_link',
            field=models.URLField(blank=True, help_text='Optional link for logo 3'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='logo_size',
            field=models.CharField(choices=[('40', 'Small (40px)'), ('50', 'Medium (50px)'), ('60', 'Standard (60px)'), ('70', 'Large (70px)'), ('80', 'Extra Large (80px)')], default='60', help_text='Size for all logos', max_length=20),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='mobile_stack_layout',
            field=models.BooleanField(default=True, help_text='Stack elements vertically on mobile'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='right_logo_1',
            field=models.ImageField(blank=True, help_text='First right logo (recommended: 60x60px)', upload_to='header/logos/right/'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='right_logo_1_alt',
            field=models.CharField(blank=True, help_text='Alt text for logo 1', max_length=100),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='right_logo_1_link',
            field=models.URLField(blank=True, help_text='Optional link for logo 1'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='right_logo_2',
            field=models.ImageField(blank=True, help_text='Second right logo (recommended: 60x60px)', upload_to='header/logos/right/'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='right_logo_2_alt',
            field=models.CharField(blank=True, help_text='Alt text for logo 2', max_length=100),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='right_logo_2_link',
            field=models.URLField(blank=True, help_text='Optional link for logo 2'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='right_logo_3',
            field=models.ImageField(blank=True, help_text='Third right logo (recommended: 60x60px)', upload_to='header/logos/right/'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='right_logo_3_alt',
            field=models.CharField(blank=True, help_text='Alt text for logo 3', max_length=100),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='right_logo_3_link',
            field=models.URLField(blank=True, help_text='Optional link for logo 3'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='show_address',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='show_affiliations',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='show_college_name',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='website_url',
            field=models.URLField(blank=True, help_text='Official website URL'),
        ),
        migrations.AddField(
            model_name='headerinfo',
            name='whatsapp_number',
            field=models.CharField(blank=True, help_text='WhatsApp number with country code (e.g., +919425540666)', max_length=20),
        ),
        migrations.AlterField(
            model_name='headerinfo',
            name='header_background_color',
            field=models.CharField(default='#ffffff', help_text='Header background color (hex code)', max_length=7),
        ),
    ]
