# Generated by Django 5.0.7 on 2025-08-27 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0010_remove_headerinfo_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True, help_text='Optional description for the menu item'),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='icon_class',
            field=models.CharField(blank=True, help_text="CSS icon class (e.g., 'fas fa-home')", max_length=50),
        ),
        migrations.AddField(
            model_name='menuitem',
            name='named_url',
            field=models.CharField(blank=True, help_text="Django URL name (e.g., 'college_website:academics')", max_length=100),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='external_url',
            field=models.URLField(blank=True, help_text='For external links'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='page',
            field=models.ForeignKey(blank=True, help_text='For CMS pages', null=True, on_delete=django.db.models.deletion.CASCADE, to='college_website.page'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='path_type',
            field=models.CharField(choices=[('internal', 'Internal Page'), ('external', 'External URL'), ('named_url', 'Named URL Pattern')], default='internal', max_length=20),
        ),
    ]
