# Generated by Django 5.0.7 on 2025-08-27 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0011_menuitem_description_menuitem_icon_class_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TopUtilityBar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Name for this utility bar configuration', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable or disable this utility bar')),
                ('background_color', models.CharField(default='#0d6efd', help_text='Background color (hex code)', max_length=20)),
                ('text_color', models.CharField(default='#ffffff', help_text='Text color (hex code)', max_length=20)),
                ('height', models.PositiveIntegerField(default=40, help_text='Height in pixels')),
                ('position', models.CharField(choices=[('top', 'Top of page'), ('below_header', 'Below header')], default='top', max_length=20)),
                ('show_social_icons', models.BooleanField(default=True, help_text='Display social media icons')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook URL')),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram URL')),
                ('youtube_url', models.URLField(blank=True, help_text='YouTube URL')),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn URL')),
                ('show_contact_info', models.BooleanField(default=True, help_text='Display contact information')),
                ('contact_phone', models.CharField(blank=True, help_text='Contact phone number', max_length=20)),
                ('contact_email', models.EmailField(blank=True, help_text='Contact email address', max_length=254)),
                ('show_custom_links', models.BooleanField(default=True, help_text='Display custom links')),
                ('custom_link_1_text', models.CharField(blank=True, help_text='Text for custom link 1', max_length=50)),
                ('custom_link_1_url', models.CharField(blank=True, help_text='URL for custom link 1', max_length=200)),
                ('custom_link_2_text', models.CharField(blank=True, help_text='Text for custom link 2', max_length=50)),
                ('custom_link_2_url', models.CharField(blank=True, help_text='URL for custom link 2', max_length=200)),
                ('custom_link_3_text', models.CharField(blank=True, help_text='Text for custom link 3', max_length=50)),
                ('custom_link_3_url', models.CharField(blank=True, help_text='URL for custom link 3', max_length=200)),
                ('show_on_mobile', models.BooleanField(default=True, help_text='Display on mobile devices')),
                ('mobile_collapsed', models.BooleanField(default=True, help_text='Collapse to icon on mobile')),
            ],
            options={
                'verbose_name': 'Top Utility Bar',
                'verbose_name_plural': 'Top Utility Bars',
            },
        ),
    ]
