# Generated by Django 5.0.7 on 2025-08-31 06:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0013_accreditationinfo_iqacfeedback_iqacinfo_iqacreport_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('full_name', models.CharField(help_text='Enter your full name', max_length=100)),
                ('email', models.EmailField(help_text='Valid email address for communication', max_length=254)),
                ('phone', models.CharField(help_text='Contact number with country code', max_length=15)),
                ('current_qualification', models.CharField(help_text='Your current highest qualification (e.g., 12th Pass, Graduate)', max_length=100)),
                ('percentage_marks', models.DecimalField(blank=True, decimal_places=2, help_text='Percentage in your latest qualification', max_digits=5, null=True)),
                ('inquiry_type', models.CharField(choices=[('general', 'General Inquiry'), ('eligibility', 'Eligibility Query'), ('documents', 'Document Requirements'), ('fees', 'Fee Structure'), ('application', 'Application Process'), ('other', 'Other')], default='general', help_text='Type of inquiry', max_length=20)),
                ('program_interest', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('not_decided', 'Not Decided Yet')], default='not_decided', help_text="Program you're interested in", max_length=20)),
                ('specific_course', models.CharField(blank=True, help_text='Specific course name if known (e.g., B.Sc Computer Science)', max_length=100)),
                ('message', models.TextField(help_text='Your specific questions or requirements')),
                ('is_responded', models.BooleanField(default=False)),
                ('response_message', models.TextField(blank=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('preferred_contact_method', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('both', 'Both')], default='email', max_length=10)),
                ('newsletter_subscription', models.BooleanField(default=False, help_text='Subscribe to college newsletter for updates')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='admission_responses', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Admission Inquiry',
                'verbose_name_plural': 'Admission Inquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
