# Generated by Django 5.0.7 on 2025-08-31 12:38

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0014_admissioninquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisionMissionContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='Vision & Mission Content', help_text='Name for this content configuration', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Make this content active')),
                ('hero_badge_text', models.CharField(default='Our Purpose & Direction', help_text='Badge text in hero section', max_length=100)),
                ('hero_title', models.CharField(default='Vision & Mission', help_text='Main hero title', max_length=200)),
                ('hero_subtitle', django_ckeditor_5.fields.CKEditor5Field(default='Guiding principles that shape our commitment to educational excellence and community transformation', help_text='Hero subtitle/description')),
                ('vision_statement', django_ckeditor_5.fields.CKEditor5Field(help_text='Main vision statement text')),
                ('vision_highlight_1', models.CharField(default='Excellence in Education', help_text='First vision highlight', max_length=100)),
                ('vision_highlight_2', models.CharField(default='Community Impact', help_text='Second vision highlight', max_length=100)),
                ('vision_highlight_3', models.CharField(default='Innovation & Research', help_text='Third vision highlight', max_length=100)),
                ('vision_highlight_4', models.CharField(default='Global Perspective', help_text='Fourth vision highlight', max_length=100)),
                ('mission_statement', django_ckeditor_5.fields.CKEditor5Field(help_text='Main mission statement text')),
                ('mission_objective_1', models.CharField(default='Deliver quality education accessible to all', help_text='First mission objective', max_length=200)),
                ('mission_objective_2', models.CharField(default='Foster research and innovation culture', help_text='Second mission objective', max_length=200)),
                ('mission_objective_3', models.CharField(default='Develop socially responsible citizens', help_text='Third mission objective', max_length=200)),
                ('cta_title', models.CharField(default='Join Our Journey', help_text='Call to action title', max_length=100)),
                ('cta_description', django_ckeditor_5.fields.CKEditor5Field(default="Be part of our mission to transform lives through education. Whether you're a prospective student, faculty member, or community partner, we welcome you to join our journey.", help_text='Call to action description')),
            ],
            options={
                'verbose_name': 'Vision & Mission Content',
                'verbose_name_plural': 'Vision & Mission Content',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CoreValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Core value title (e.g., Excellence, Integrity)', max_length=50)),
                ('description', models.TextField(help_text='Description of this core value')),
                ('icon_class', models.CharField(default='fas fa-star', help_text='FontAwesome icon class', max_length=50)),
                ('gradient_color', models.CharField(choices=[('yellow-orange', 'Yellow to Orange'), ('blue-indigo', 'Blue to Indigo'), ('purple-pink', 'Purple to Pink'), ('green-emerald', 'Green to Emerald'), ('teal-cyan', 'Teal to Cyan'), ('red-pink', 'Red to Pink')], default='blue-indigo', help_text='Gradient color scheme', max_length=20)),
                ('ordering', models.IntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('is_active', models.BooleanField(default=True, help_text='Show this core value')),
                ('vision_mission_content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='core_values', to='college_website.visionmissioncontent')),
            ],
            options={
                'verbose_name': 'Core Value',
                'verbose_name_plural': 'Core Values',
                'ordering': ['ordering', 'title'],
            },
        ),
    ]
