# Generated by Django 5.0.7 on 2025-08-31 16:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0016_historycontent_milestone_timelineevent'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoryGalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Title or caption for the image', max_length=200)),
                ('image', models.ImageField(help_text='Gallery image (recommended: 800x600px or higher)', upload_to='history/gallery/')),
                ('category', models.CharField(choices=[('campus', 'Campus Life'), ('events', 'Events & Celebrations'), ('academics', 'Academic Activities'), ('sports', 'Sports & Recreation'), ('cultural', 'Cultural Programs'), ('achievements', 'Achievements & Awards'), ('infrastructure', 'Infrastructure & Facilities'), ('alumni', 'Alumni Gatherings'), ('historical', 'Historical Moments')], default='campus', help_text='Category for organizing images', max_length=50)),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the image')),
                ('year_taken', models.PositiveIntegerField(blank=True, help_text='Year when this photo was taken (optional)', null=True)),
                ('photographer', models.CharField(blank=True, help_text='Photographer credit (optional)', max_length=100)),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Order of display (lower numbers appear first)')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured image (appears prominently)')),
                ('is_active', models.BooleanField(default=True, help_text='Include this image in the gallery')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('history_content', models.ForeignKey(help_text='History content this image belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='college_website.historycontent')),
            ],
            options={
                'verbose_name': 'History Gallery Image',
                'verbose_name_plural': 'History Gallery Images',
                'ordering': ['category', 'ordering', '-year_taken'],
            },
        ),
    ]
