# Generated by Django 5.0.7 on 2025-08-31 17:21

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0017_historygalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='accreditation',
            field=models.CharField(blank=True, help_text='Accreditation details (e.g., UGC, AICTE)', max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='admission_process',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed admission process'),
        ),
        migrations.AddField(
            model_name='program',
            name='average_salary',
            field=models.CharField(blank=True, help_text='Expected salary range (e.g., ₹3-5 LPA)', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='career_opportunities',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Career prospects and job opportunities'),
        ),
        migrations.AddField(
            model_name='program',
            name='core_subjects',
            field=models.TextField(blank=True, help_text='List of core subjects (one per line)'),
        ),
        migrations.AddField(
            model_name='program',
            name='curriculum',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed curriculum information'),
        ),
        migrations.AddField(
            model_name='program',
            name='degree_type',
            field=models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate', 'Postgraduate'), ('diploma', 'Diploma'), ('certificate', 'Certificate')], default='undergraduate', max_length=20),
        ),
        migrations.AddField(
            model_name='program',
            name='department',
            field=models.CharField(blank=True, help_text='Department offering this program', max_length=100),
        ),
        migrations.AddField(
            model_name='program',
            name='elective_subjects',
            field=models.TextField(blank=True, help_text='List of elective subjects (one per line)'),
        ),
        migrations.AddField(
            model_name='program',
            name='eligibility',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Eligibility criteria and requirements'),
        ),
        migrations.AddField(
            model_name='program',
            name='entrance_exam',
            field=models.CharField(blank=True, help_text='Required entrance exam (if any)', max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year when program was established', null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='fees',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual fees in INR', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Feature this program on homepage'),
        ),
        migrations.AddField(
            model_name='program',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='program',
            name='minimum_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum percentage required', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='program_image',
            field=models.ImageField(blank=True, help_text='Program representative image', upload_to='programs/images/'),
        ),
        migrations.AddField(
            model_name='program',
            name='scholarship_available',
            field=models.BooleanField(default=False, help_text='Scholarships available for this program'),
        ),
        migrations.AddField(
            model_name='program',
            name='scholarship_details',
            field=models.TextField(blank=True, help_text='Details about available scholarships'),
        ),
        migrations.AddField(
            model_name='program',
            name='short_name',
            field=models.CharField(blank=True, help_text='Abbreviated name (e.g., B.A., B.Sc.)', max_length=50),
        ),
        migrations.AddField(
            model_name='program',
            name='top_recruiters',
            field=models.TextField(blank=True, help_text='List of top recruiting companies (one per line)'),
        ),
        migrations.AddField(
            model_name='program',
            name='total_seats',
            field=models.PositiveIntegerField(blank=True, help_text='Total available seats', null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='brochure',
            field=models.FileField(blank=True, help_text='Program brochure PDF', upload_to='programs/brochures/'),
        ),
        migrations.AlterField(
            model_name='program',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed program description'),
        ),
        migrations.AlterField(
            model_name='program',
            name='duration',
            field=models.CharField(blank=True, help_text='Program duration (e.g., 3 years)', max_length=50),
        ),
        migrations.AlterField(
            model_name='program',
            name='name',
            field=models.CharField(help_text='Full program name', max_length=200),
        ),
    ]
