# Generated by Django 5.0.7 on 2025-09-01 07:16

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0018_program_accreditation_program_admission_process_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Department name (e.g., Department of Physics)', max_length=200)),
                ('short_name', models.CharField(blank=True, help_text='Abbreviated name (e.g., Physics Dept.)', max_length=50)),
                ('discipline', models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce'), ('management', 'Management'), ('other', 'Other')], help_text='Primary discipline this department belongs to', max_length=20)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed description of the department')),
                ('vision', models.TextField(blank=True, help_text="Department's vision statement")),
                ('mission', models.TextField(blank=True, help_text="Department's mission statement")),
                ('established_year', models.PositiveIntegerField(blank=True, help_text='Year when department was established', null=True)),
                ('head_of_department', models.CharField(blank=True, help_text='Current Head of Department name', max_length=100)),
                ('hod_qualification', models.CharField(blank=True, help_text="HOD's qualifications", max_length=200)),
                ('hod_message', models.TextField(blank=True, help_text='Message from Head of Department')),
                ('total_faculty', models.PositiveIntegerField(default=0, help_text='Total number of faculty members')),
                ('total_students', models.PositiveIntegerField(default=0, help_text='Total number of students enrolled')),
                ('laboratories', models.TextField(blank=True, help_text='List of laboratories (one per line)')),
                ('facilities', models.TextField(blank=True, help_text='Department facilities and infrastructure')),
                ('programs_offered', models.TextField(blank=True, help_text='List of programs offered by this department (one per line)')),
                ('research_areas', models.TextField(blank=True, help_text='Key research areas (one per line)')),
                ('achievements', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Department achievements and recognitions')),
                ('publications', models.TextField(blank=True, help_text='Notable publications and research papers')),
                ('office_location', models.CharField(blank=True, help_text='Department office location', max_length=200)),
                ('phone', models.CharField(blank=True, help_text='Department contact phone', max_length=20)),
                ('email', models.EmailField(blank=True, help_text='Department contact email', max_length=254)),
                ('department_image', models.ImageField(blank=True, help_text='Department representative image', upload_to='departments/')),
                ('hod_image', models.ImageField(blank=True, help_text='Head of Department photo', upload_to='departments/hod/')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this department on homepage')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers appear first)')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['ordering', 'discipline', 'name'],
            },
        ),
    ]
