# Generated by Django 5.0.7 on 2025-09-01 09:49

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0019_department'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['ordering', 'name'], 'verbose_name': 'Department', 'verbose_name_plural': 'Departments'},
        ),
        migrations.RemoveField(
            model_name='department',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='department',
            name='publications',
        ),
        migrations.RemoveField(
            model_name='department',
            name='total_faculty',
        ),
        migrations.RemoveField(
            model_name='department',
            name='total_students',
        ),
        migrations.AddField(
            model_name='department',
            name='alumni_count',
            field=models.PositiveIntegerField(default=0, help_text='Total alumni count'),
        ),
        migrations.AddField(
            model_name='department',
            name='banner_image',
            field=models.ImageField(blank=True, help_text='Hero section banner image', null=True, upload_to='departments/banners/'),
        ),
        migrations.AddField(
            model_name='department',
            name='brochure',
            field=models.FileField(blank=True, help_text='Department brochure PDF', null=True, upload_to='departments/documents/'),
        ),
        migrations.AddField(
            model_name='department',
            name='department_logo',
            field=models.ImageField(blank=True, help_text='Department logo/emblem', null=True, upload_to='departments/logos/'),
        ),
        migrations.AddField(
            model_name='department',
            name='faculty_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of faculty members'),
        ),
        migrations.AddField(
            model_name='department',
            name='hod_designation',
            field=models.CharField(blank=True, help_text="HOD's designation", max_length=100),
        ),
        migrations.AddField(
            model_name='department',
            name='meta_description',
            field=models.TextField(blank=True, help_text='SEO description', max_length=300),
        ),
        migrations.AddField(
            model_name='department',
            name='meta_keywords',
            field=models.CharField(blank=True, help_text='SEO keywords, comma-separated', max_length=500),
        ),
        migrations.AddField(
            model_name='department',
            name='meta_title',
            field=models.CharField(blank=True, help_text='SEO title', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='short_description',
            field=models.TextField(blank=True, help_text='Brief description for listings', max_length=500),
        ),
        migrations.AddField(
            model_name='department',
            name='student_count',
            field=models.PositiveIntegerField(default=0, help_text='Current student enrollment'),
        ),
        migrations.AddField(
            model_name='department',
            name='syllabus',
            field=models.FileField(blank=True, help_text='Syllabus PDF', null=True, upload_to='departments/documents/'),
        ),
        migrations.AddField(
            model_name='department',
            name='tagline',
            field=models.CharField(blank=True, help_text='Department tagline or motto', max_length=200),
        ),
        migrations.AddField(
            model_name='department',
            name='theme_color',
            field=models.CharField(choices=[('blue', 'Blue Theme'), ('green', 'Green Theme'), ('red', 'Red Theme'), ('purple', 'Purple Theme'), ('orange', 'Orange Theme'), ('teal', 'Teal Theme'), ('indigo', 'Indigo Theme'), ('pink', 'Pink Theme'), ('yellow', 'Yellow Theme'), ('gray', 'Gray Theme')], default='blue', help_text='Primary color theme for department pages', max_length=20),
        ),
        migrations.AddField(
            model_name='department',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='achievements',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Department achievements and recognition'),
        ),
        migrations.AlterField(
            model_name='department',
            name='department_image',
            field=models.ImageField(blank=True, help_text='Main department image', null=True, upload_to='departments/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='description',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Detailed department description'),
        ),
        migrations.AlterField(
            model_name='department',
            name='discipline',
            field=models.CharField(choices=[('science', 'Science'), ('arts', 'Arts'), ('commerce', 'Commerce'), ('management', 'Management'), ('other', 'Other')], help_text='Primary discipline', max_length=20),
        ),
        migrations.AlterField(
            model_name='department',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='department',
            name='established_year',
            field=models.PositiveIntegerField(blank=True, help_text='Year established', null=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='facilities',
            field=models.TextField(blank=True, help_text='Department facilities, one per line'),
        ),
        migrations.AlterField(
            model_name='department',
            name='head_of_department',
            field=models.CharField(blank=True, help_text='Name of HOD', max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod_image',
            field=models.ImageField(blank=True, null=True, upload_to='departments/hod/'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod_message',
            field=models.TextField(blank=True, help_text='Message from HOD'),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod_qualification',
            field=models.CharField(blank=True, help_text="HOD's qualifications", max_length=500),
        ),
        migrations.AlterField(
            model_name='department',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in featured departments'),
        ),
        migrations.AlterField(
            model_name='department',
            name='laboratories',
            field=models.TextField(blank=True, help_text='Lab facilities, one per line'),
        ),
        migrations.AlterField(
            model_name='department',
            name='mission',
            field=models.TextField(blank=True, help_text='Department mission statement'),
        ),
        migrations.AlterField(
            model_name='department',
            name='office_location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='department',
            name='ordering',
            field=models.PositiveIntegerField(default=0, help_text='Display order'),
        ),
        migrations.AlterField(
            model_name='department',
            name='programs_offered',
            field=models.TextField(blank=True, help_text='List programs, one per line'),
        ),
        migrations.AlterField(
            model_name='department',
            name='research_areas',
            field=models.TextField(blank=True, help_text='Research focus areas, one per line'),
        ),
        migrations.AlterField(
            model_name='department',
            name='slug',
            field=models.SlugField(help_text='URL-friendly version of name', unique=True),
        ),
        migrations.AlterField(
            model_name='department',
            name='vision',
            field=models.TextField(blank=True, help_text='Department vision statement'),
        ),
        migrations.CreateModel(
            name='DepartmentEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of title')),
                ('event_type', models.CharField(choices=[('seminar', 'Seminar'), ('workshop', 'Workshop'), ('conference', 'Conference'), ('guest_lecture', 'Guest Lecture'), ('research_presentation', 'Research Presentation'), ('cultural', 'Cultural Event'), ('sports', 'Sports Event'), ('achievement', 'Achievement/Award'), ('other', 'Other')], default='seminar', max_length=30)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed event description')),
                ('short_description', models.TextField(blank=True, help_text='Brief description for listings', max_length=300)),
                ('event_date', models.DateField(help_text='Event date')),
                ('start_time', models.TimeField(blank=True, help_text='Event start time', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='Event end time', null=True)),
                ('venue', models.CharField(blank=True, help_text='Event venue', max_length=200)),
                ('location_details', models.TextField(blank=True, help_text='Additional location information')),
                ('organizer', models.CharField(blank=True, help_text='Event organizer', max_length=200)),
                ('speaker', models.CharField(blank=True, help_text='Guest speaker/presenter', max_length=200)),
                ('speaker_bio', models.TextField(blank=True, help_text='Speaker biography')),
                ('featured_image', models.ImageField(blank=True, null=True, upload_to='events/departments/')),
                ('registration_required', models.BooleanField(default=False)),
                ('registration_link', models.URLField(blank=True, help_text='External registration link')),
                ('max_participants', models.PositiveIntegerField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured events')),
                ('show_on_homepage', models.BooleanField(default=False, help_text='Display on college homepage')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', max_length=300)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='department_events', to='college_website.department')),
                ('gallery_images', models.ManyToManyField(blank=True, help_text='Event gallery images', to='college_website.galleryphoto')),
            ],
            options={
                'verbose_name': 'Department Event',
                'verbose_name_plural': 'Department Events',
                'ordering': ['-event_date', '-created_at'],
                'unique_together': {('department', 'slug')},
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of faculty member', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of name', unique=True)),
                ('designation', models.CharField(choices=[('professor', 'Professor'), ('associate_professor', 'Associate Professor'), ('assistant_professor', 'Assistant Professor'), ('lecturer', 'Lecturer'), ('visiting_faculty', 'Visiting Faculty'), ('emeritus', 'Professor Emeritus'), ('other', 'Other')], max_length=30)),
                ('designation_order', models.PositiveIntegerField(default=0, help_text='Order for display (lower first)')),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID', max_length=50)),
                ('highest_qualification', models.CharField(choices=[('phd', 'Ph.D'), ('mphil', 'M.Phil'), ('masters', 'Masters'), ('bachelors', 'Bachelors'), ('other', 'Other')], default='masters', max_length=20)),
                ('qualifications', models.TextField(help_text='Detailed qualifications')),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('joining_date', models.DateField(blank=True, help_text='Date of joining institution', null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('research_interests', models.TextField(blank=True, help_text='Research interests, one per line')),
                ('publications', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Publications and research papers')),
                ('courses_taught', models.TextField(blank=True, help_text='Courses taught, one per line')),
                ('photo', models.ImageField(blank=True, help_text='Faculty photo', null=True, upload_to='faculty/')),
                ('cv_file', models.FileField(blank=True, help_text='CV/Resume PDF', null=True, upload_to='faculty/cv/')),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Faculty biography')),
                ('message', models.TextField(blank=True, help_text='Message to students')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured faculty')),
                ('show_on_website', models.BooleanField(default=True, help_text='Display on public website')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', max_length=300)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faculty_members', to='college_website.department')),
            ],
            options={
                'verbose_name': 'Faculty Member',
                'verbose_name_plural': 'Faculty Members',
                'ordering': ['department', 'designation_order', 'name'],
                'unique_together': {('department', 'slug')},
            },
        ),
    ]
