# Generated by Django 5.0.7 on 2025-09-02 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0020_alter_department_options_remove_department_phone_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='JazzminCustomization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customization_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jazzmin_customizations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Jazzmin Customization',
                'verbose_name_plural': 'Jazzmin Customizations',
                'unique_together': {('user',)},
            },
        ),
    ]
