# Generated by Django 5.0.7 on 2025-09-03 02:35

import colorfield.fields
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0021_jazzmincustomization'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroBanner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Main hero title', max_length=200)),
                ('subtitle', models.TextField(blank=True, help_text='Hero subtitle/description')),
                ('primary_button_text', models.CharField(blank=True, help_text='Primary button text', max_length=50)),
                ('primary_button_url', models.URLField(blank=True, help_text='Primary button link')),
                ('secondary_button_text', models.CharField(blank=True, help_text='Secondary button text', max_length=50)),
                ('secondary_button_url', models.URLField(blank=True, help_text='Secondary button link')),
                ('background_type', models.CharField(choices=[('gradient', 'Gradient'), ('solid', 'Solid Color'), ('image', 'Background Image'), ('video', 'Background Video')], default='gradient', help_text='Choose background type', max_length=20)),
                ('gradient_start_color', colorfield.fields.ColorField(default='#1e3a8a', help_text='Gradient start color', image_field=None, max_length=25, samples=None)),
                ('gradient_end_color', colorfield.fields.ColorField(default='#7c3aed', help_text='Gradient end color', image_field=None, max_length=25, samples=None)),
                ('gradient_direction', models.CharField(choices=[('to right', 'Horizontal'), ('to bottom', 'Vertical'), ('to bottom right', 'Diagonal'), ('135deg', 'Angled')], default='135deg', help_text='Gradient direction', max_length=20)),
                ('solid_background_color', colorfield.fields.ColorField(default='#1e3a8a', help_text='Solid background color', image_field=None, max_length=25, samples=None)),
                ('background_image', models.ImageField(blank=True, help_text='Background image (optional)', null=True, upload_to='hero_banner/')),
                ('background_image_opacity', models.IntegerField(default=100, help_text='Background image opacity (0-100)', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('background_video_url', models.URLField(blank=True, help_text='Background video URL (YouTube/Vimeo)')),
                ('title_font_family', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Playfair Display', 'Playfair Display')], default='Inter', help_text='Title font family', max_length=50)),
                ('title_font_size', models.CharField(choices=[('text-4xl', 'Small (36px)'), ('text-5xl', 'Medium (48px)'), ('text-6xl', 'Large (60px)'), ('text-7xl', 'Extra Large (72px)'), ('text-8xl', 'Huge (96px)')], default='text-6xl', help_text='Title font size', max_length=20)),
                ('title_font_weight', models.CharField(choices=[('font-light', 'Light'), ('font-normal', 'Normal'), ('font-medium', 'Medium'), ('font-semibold', 'Semi Bold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extra Bold')], default='font-bold', help_text='Title font weight', max_length=20)),
                ('subtitle_font_family', models.CharField(choices=[('Inter', 'Inter'), ('Roboto', 'Roboto'), ('Open Sans', 'Open Sans'), ('Poppins', 'Poppins'), ('Montserrat', 'Montserrat'), ('Playfair Display', 'Playfair Display')], default='Inter', help_text='Subtitle font family', max_length=50)),
                ('subtitle_font_size', models.CharField(choices=[('text-lg', 'Small (18px)'), ('text-xl', 'Medium (20px)'), ('text-2xl', 'Large (24px)'), ('text-3xl', 'Extra Large (30px)')], default='text-xl', help_text='Subtitle font size', max_length=20)),
                ('title_color', colorfield.fields.ColorField(default='#ffffff', help_text='Title text color', image_field=None, max_length=25, samples=None)),
                ('subtitle_color', colorfield.fields.ColorField(default='#e5e7eb', help_text='Subtitle text color', image_field=None, max_length=25, samples=None)),
                ('primary_button_bg_color', colorfield.fields.ColorField(default='#dc2626', help_text='Primary button background color', image_field=None, max_length=25, samples=None)),
                ('primary_button_text_color', colorfield.fields.ColorField(default='#ffffff', help_text='Primary button text color', image_field=None, max_length=25, samples=None)),
                ('secondary_button_bg_color', colorfield.fields.ColorField(default='transparent', help_text='Secondary button background color', image_field=None, max_length=25, samples=None)),
                ('secondary_button_text_color', colorfield.fields.ColorField(default='#ffffff', help_text='Secondary button text color', image_field=None, max_length=25, samples=None)),
                ('secondary_button_border_color', colorfield.fields.ColorField(default='#ffffff', help_text='Secondary button border color', image_field=None, max_length=25, samples=None)),
                ('padding_top', models.CharField(choices=[('py-8', 'Small (32px)'), ('py-12', 'Medium (48px)'), ('py-16', 'Large (64px)'), ('py-20', 'Extra Large (80px)'), ('py-24', 'Huge (96px)')], default='py-16', help_text='Vertical padding', max_length=20)),
                ('content_alignment', models.CharField(choices=[('text-left', 'Left'), ('text-center', 'Center'), ('text-right', 'Right')], default='text-center', help_text='Content alignment', max_length=20)),
                ('enable_animations', models.BooleanField(default=True, help_text='Enable entrance animations')),
                ('animation_duration', models.CharField(choices=[('duration-500', 'Fast (0.5s)'), ('duration-700', 'Medium (0.7s)'), ('duration-1000', 'Slow (1s)')], default='duration-700', help_text='Animation duration', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Enable this hero banner')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Hero Banner',
                'verbose_name_plural': 'Hero Banners',
                'ordering': ['order', '-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='JazzminCustomization',
        ),
    ]
