# Generated by Django 5.0.7 on 2025-09-03 05:32

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0022_herobanner_delete_jazzmincustomization'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='accred_1_color',
            field=colorfield.fields.ColorField(default='#2563eb', help_text='First accreditation color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='accred_1_icon',
            field=models.CharField(default='fas fa-star', help_text='Icon for first accreditation', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='accred_1_text',
            field=models.CharField(default='UGC Recognized', help_text='First accreditation text', max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='accred_2_color',
            field=colorfield.fields.ColorField(default='#7c3aed', help_text='Second accreditation color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='accred_2_icon',
            field=models.CharField(default='fas fa-star', help_text='Icon for second accreditation', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='accred_2_text',
            field=models.CharField(default='NAAC Grade A', help_text='Second accreditation text', max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='accred_3_color',
            field=colorfield.fields.ColorField(default='#2563eb', help_text='Third accreditation color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='accred_3_icon',
            field=models.CharField(default='fas fa-map-marker-alt', help_text='Icon for third accreditation', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='accred_3_text',
            field=models.CharField(default='3 Star IIC Rating', help_text='Third accreditation text', max_length=100),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='show_accreditations',
            field=models.BooleanField(default=True, help_text='Show accreditation badges'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='show_statistics',
            field=models.BooleanField(default=True, help_text='Show statistics cards'),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_1_color',
            field=colorfield.fields.ColorField(default='#2563eb', help_text='First stat card color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_1_icon',
            field=models.CharField(default='fas fa-calendar-alt', help_text='Icon class for first stat (e.g., fas fa-calendar-alt)', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_1_label',
            field=models.CharField(default='Years Experience', help_text='First statistic label', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_1_number',
            field=models.CharField(default='25+', help_text='First statistic number', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_2_color',
            field=colorfield.fields.ColorField(default='#7c3aed', help_text='Second stat card color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_2_icon',
            field=models.CharField(default='fas fa-users', help_text='Icon class for second stat (e.g., fas fa-calendar-alt)', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_2_label',
            field=models.CharField(default='Students', help_text='Second statistic label', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_2_number',
            field=models.CharField(default='8000+', help_text='Second statistic number', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_3_color',
            field=colorfield.fields.ColorField(default='#2563eb', help_text='Third stat card color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_3_icon',
            field=models.CharField(default='fas fa-book-open', help_text='Icon class for third stat (e.g., fas fa-calendar-alt)', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_3_label',
            field=models.CharField(default='Courses', help_text='Third statistic label', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_3_number',
            field=models.CharField(default='18+', help_text='Third statistic number', max_length=20),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_4_color',
            field=colorfield.fields.ColorField(default='#7c3aed', help_text='Fourth stat card color', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_4_icon',
            field=models.CharField(default='fas fa-lock', help_text='Icon class for fourth stat (e.g., fas fa-calendar-alt)', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_4_label',
            field=models.CharField(default='Placement', help_text='Fourth statistic label', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='stat_4_number',
            field=models.CharField(default='95%', help_text='Fourth statistic number', max_length=50),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_highlight_color',
            field=colorfield.fields.ColorField(default='#fbbf24', help_text='Color for highlighted title text (hex code)', image_field=None, max_length=25, samples=None),
        ),
        migrations.AddField(
            model_name='herobanner',
            name='title_highlight_text',
            field=models.CharField(blank=True, help_text="Text to highlight with different color (e.g., '18+ Courses')", max_length=100),
        ),
    ]
