# Generated by Django 5.0.7 on 2025-09-03 16:27

import colorfield.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0023_herobanner_accred_1_color_herobanner_accred_1_icon_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamTimetable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text="Name for this timetable (e.g., 'Semester 1 2024')", max_length=200)),
                ('academic_year', models.CharField(help_text="Academic year (e.g., '2024-2025')", max_length=20)),
                ('semester', models.CharField(help_text="Semester (e.g., '1st', '2nd', '3rd', '4th')", max_length=20)),
                ('header_title', models.CharField(default='Exam Timetable', help_text='Main header title', max_length=200)),
                ('header_subtitle', models.CharField(default='View and manage examination schedules efficiently', help_text='Header subtitle', max_length=300)),
                ('header_gradient_start', colorfield.fields.ColorField(default='#3b82f6', help_text='Header gradient start color', image_field=None, max_length=25, samples=None)),
                ('header_gradient_end', colorfield.fields.ColorField(default='#4f46e5', help_text='Header gradient end color', image_field=None, max_length=25, samples=None)),
                ('exam_guidelines', models.TextField(blank=True, help_text='Exam guidelines and rules')),
                ('morning_session_start', models.TimeField(default='09:00', help_text='Morning session start time')),
                ('morning_session_end', models.TimeField(default='12:00', help_text='Morning session end time')),
                ('afternoon_session_start', models.TimeField(default='14:00', help_text='Afternoon session start time')),
                ('afternoon_session_end', models.TimeField(default='17:00', help_text='Afternoon session end time')),
                ('break_duration', models.CharField(default='2 hours', help_text='Break duration description', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Enable this timetable')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured timetable')),
            ],
            options={
                'verbose_name': 'Exam Timetable',
                'verbose_name_plural': 'Exam Timetables',
                'ordering': ['-academic_year', 'semester', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExamTimetableWeek',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('week_number', models.PositiveIntegerField(help_text='Week number (1, 2, 3, 4)')),
                ('week_title', models.CharField(default='', help_text='Custom week title (optional)', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Enable this week')),
                ('timetable', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weeks', to='college_website.examtimetable')),
            ],
            options={
                'verbose_name': 'Exam Timetable Week',
                'verbose_name_plural': 'Exam Timetable Weeks',
                'ordering': ['week_number'],
                'unique_together': {('timetable', 'week_number')},
            },
        ),
        migrations.CreateModel(
            name='ExamTimetableTimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('start_time', models.TimeField(help_text='Start time for this slot')),
                ('end_time', models.TimeField(help_text='End time for this slot')),
                ('is_active', models.BooleanField(default=True, help_text='Enable this time slot')),
                ('week', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_slots', to='college_website.examtimetableweek')),
            ],
            options={
                'verbose_name': 'Exam Timetable Time Slot',
                'verbose_name_plural': 'Exam Timetable Time Slots',
                'ordering': ['start_time'],
            },
        ),
        migrations.CreateModel(
            name='ExamTimetableExam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], help_text='Day of the week', max_length=20)),
                ('subject_name', models.CharField(help_text='Subject name', max_length=200)),
                ('room_number', models.CharField(help_text='Room number or lab name', max_length=50)),
                ('duration', models.CharField(help_text="Exam duration (e.g., '2 hours', '3 hours')", max_length=50)),
                ('semester', models.CharField(help_text="Semester (e.g., '1st', '2nd', '3rd', '4th')", max_length=20)),
                ('priority', models.CharField(choices=[('urgent', 'Urgent'), ('important', 'Important'), ('general', 'General')], default='general', help_text='Exam priority', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured exam')),
                ('background_color', colorfield.fields.ColorField(default='#f3f4f6', help_text='Background color for exam slot', image_field=None, max_length=25, samples=None)),
                ('border_color', colorfield.fields.ColorField(default='#3b82f6', help_text='Left border color', image_field=None, max_length=25, samples=None)),
                ('text_color', colorfield.fields.ColorField(default='#1f2937', help_text='Text color', image_field=None, max_length=25, samples=None)),
                ('is_active', models.BooleanField(default=True, help_text='Enable this exam')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='college_website.examtimetabletimeslot')),
            ],
            options={
                'verbose_name': 'Exam Timetable Exam',
                'verbose_name_plural': 'Exam Timetable Exams',
                'ordering': ['day_of_week', 'time_slot__start_time'],
                'unique_together': {('time_slot', 'day_of_week')},
            },
        ),
    ]
