# Generated by Django 5.0.7 on 2025-09-04 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0025_menucategory_menuvisibilitysettings_menusubmenu'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_about_section',
            field=models.BooleanField(default=True, help_text='Show About section'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_academic_events',
            field=models.BooleanField(default=True, help_text='Show Academic Events'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_academics_calendar',
            field=models.BooleanField(default=True, help_text='Show Academic Calendar'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_academics_departments',
            field=models.BooleanField(default=True, help_text='Show Academic Departments'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_academics_library',
            field=models.BooleanField(default=True, help_text='Show Library'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_academics_programs',
            field=models.BooleanField(default=True, help_text='Show Academic Programs'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_admissions_application',
            field=models.BooleanField(default=True, help_text='Show Online Application'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_admissions_courses',
            field=models.BooleanField(default=True, help_text='Show Courses Offered'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_admissions_eligibility',
            field=models.BooleanField(default=True, help_text='Show Admission Eligibility'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_admissions_fees',
            field=models.BooleanField(default=True, help_text='Show Fee Structure'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_admissions_guidelines',
            field=models.BooleanField(default=True, help_text='Show Admission Guidelines'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_admissions_process',
            field=models.BooleanField(default=True, help_text='Show Admission Process'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_admissions_prospectus',
            field=models.BooleanField(default=True, help_text='Show Prospectus'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_admissions_scholarships',
            field=models.BooleanField(default=True, help_text='Show Scholarships'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_annual_reports',
            field=models.BooleanField(default=True, help_text='Show Annual Reports'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_contact_section',
            field=models.BooleanField(default=True, help_text='Show Contact section'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_exam_notices',
            field=models.BooleanField(default=True, help_text='Show Exam Notices'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_exam_results',
            field=models.BooleanField(default=True, help_text='Show Exam Results'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_extracurricular_events',
            field=models.BooleanField(default=True, help_text='Show Extracurricular Events'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_gallery',
            field=models.BooleanField(default=True, help_text='Show Gallery'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_news_announcements',
            field=models.BooleanField(default=True, help_text='Show News & Announcements'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_notices_section',
            field=models.BooleanField(default=True, help_text='Show Notices section'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_research_collaborations',
            field=models.BooleanField(default=True, help_text='Show Collaborations & MOUs'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_research_consultancy',
            field=models.BooleanField(default=True, help_text='Show Consultancy'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_research_innovation',
            field=models.BooleanField(default=True, help_text='Show Innovation & Incubation'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_student_library',
            field=models.BooleanField(default=True, help_text='Show Student Library'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_student_portal_main',
            field=models.BooleanField(default=True, help_text='Show Student Portal Main'),
        ),
    ]
