# Generated by Django 5.0.7 on 2025-09-04 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0026_menuvisibilitysettings_show_about_section_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_academics_overview',
            field=models.BooleanField(default=True, help_text='Show Academic Overview'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_arts_stream',
            field=models.BooleanField(default=True, help_text='Show Arts Stream'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_commerce_stream',
            field=models.BooleanField(default=True, help_text='Show Commerce Stream'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_program_brochures',
            field=models.BooleanField(default=True, help_text='Show Program Brochures'),
        ),
        migrations.AddField(
            model_name='menuvisibilitysettings',
            name='show_science_stream',
            field=models.BooleanField(default=True, help_text='Show Science Stream'),
        ),
        migrations.AlterField(
            model_name='menuvisibilitysettings',
            name='show_academics_library',
            field=models.BooleanField(default=True, help_text='Show Library & Resources'),
        ),
    ]
