# Generated by Django 5.0.7 on 2025-09-05 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0027_menuvisibilitysettings_show_academics_overview_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menuvisibilitysettings',
            name='show_academics_overview',
        ),
        migrations.RemoveField(
            model_name='menuvisibilitysettings',
            name='show_arts_stream',
        ),
        migrations.RemoveField(
            model_name='menuvisibilitysettings',
            name='show_commerce_stream',
        ),
        migrations.RemoveField(
            model_name='menuvisibilitysettings',
            name='show_program_brochures',
        ),
        migrations.RemoveField(
            model_name='menuvisibilitysettings',
            name='show_science_stream',
        ),
        migrations.AlterField(
            model_name='menuvisibilitysettings',
            name='show_academics_library',
            field=models.BooleanField(default=True, help_text='Show Library'),
        ),
        migrations.CreateModel(
            name='QuestionPaper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Question paper title (e.g., Mathematics - 1st Semester)', max_length=200)),
                ('subject', models.CharField(choices=[('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('computer-science', 'Computer Science'), ('english', 'English'), ('economics', 'Economics'), ('business-studies', 'Business Studies'), ('accountancy', 'Accountancy'), ('statistics', 'Statistics'), ('biology', 'Biology'), ('history', 'History'), ('political-science', 'Political Science'), ('sociology', 'Sociology'), ('psychology', 'Psychology'), ('geography', 'Geography'), ('other', 'Other')], help_text='Subject name', max_length=50)),
                ('semester', models.CharField(choices=[('1', '1st Semester'), ('2', '2nd Semester'), ('3', '3rd Semester'), ('4', '4th Semester'), ('5', '5th Semester'), ('6', '6th Semester')], help_text='Semester', max_length=10)),
                ('degree_type', models.CharField(choices=[('bsc', 'B.Sc'), ('bcom', 'B.Com'), ('ba', 'B.A'), ('bca', 'BCA'), ('bba', 'BBA'), ('msc', 'M.Sc'), ('mcom', 'M.Com'), ('ma', 'M.A'), ('mca', 'MCA'), ('mba', 'MBA'), ('other', 'Other')], help_text='Degree type', max_length=20)),
                ('academic_year', models.CharField(help_text='Academic year (e.g., 2024-2025)', max_length=20)),
                ('question_paper_file', models.FileField(help_text='Upload question paper PDF', upload_to='question_papers/')),
                ('file_size', models.CharField(blank=True, help_text='File size (auto-calculated)', max_length=20)),
                ('description', models.TextField(blank=True, help_text='Brief description of the question paper')),
                ('exam_date', models.DateField(blank=True, help_text='Date when the exam was conducted', null=True)),
                ('duration', models.CharField(blank=True, help_text='Exam duration (e.g., 3 hours)', max_length=50)),
                ('total_marks', models.PositiveIntegerField(blank=True, help_text='Total marks for the exam', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Make this question paper visible to students')),
                ('is_featured', models.BooleanField(default=False, help_text='Mark as featured question paper')),
                ('download_count', models.PositiveIntegerField(default=0, help_text='Number of times downloaded')),
                ('slug', models.SlugField(blank=True, help_text='URL-friendly version of title', unique=True)),
            ],
            options={
                'verbose_name': 'Question Paper',
                'verbose_name_plural': 'Question Papers',
                'ordering': ['-academic_year', 'semester', 'subject', 'title'],
                'unique_together': {('subject', 'semester', 'degree_type', 'academic_year')},
            },
        ),
    ]
