# Generated by Django 5.0.7 on 2025-09-05 08:36

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0028_remove_menuvisibilitysettings_show_academics_overview_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevaluationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Revaluation', help_text='Page title', max_length=200)),
                ('subtitle', models.CharField(default='Apply for revaluation of your examination papers', help_text='Page subtitle', max_length=300)),
                ('step1_title', models.CharField(default='Download Form', help_text='Step 1 title', max_length=100)),
                ('step1_description', models.TextField(default='Download the revaluation application form from the college website or collect it from the examination office.', help_text='Step 1 description')),
                ('step2_title', models.CharField(default='Fill Application', help_text='Step 2 title', max_length=100)),
                ('step2_description', models.TextField(default='Complete the application form with all required details including subject codes and paper details.', help_text='Step 2 description')),
                ('step3_title', models.CharField(default='Pay Fees', help_text='Step 3 title', max_length=100)),
                ('step3_description', models.TextField(default='Pay the prescribed revaluation fees at the college office or through online payment methods.', help_text='Step 3 description')),
                ('step4_title', models.CharField(default='Submit Application', help_text='Step 4 title', max_length=100)),
                ('step4_description', models.TextField(default='Submit the completed form along with fee receipt to the examination office within the specified deadline.', help_text='Step 4 description')),
                ('theory_paper_fee', models.DecimalField(decimal_places=2, default=500.0, help_text='Fee for theory papers', max_digits=8)),
                ('practical_paper_fee', models.DecimalField(decimal_places=2, default=750.0, help_text='Fee for practical papers', max_digits=8)),
                ('project_fee', models.DecimalField(decimal_places=2, default=1000.0, help_text='Fee for project reports', max_digits=8)),
                ('application_period', models.CharField(default='15 days from result declaration', help_text='Application period', max_length=100)),
                ('processing_time', models.CharField(default='30-45 days', help_text='Processing time', max_length=100)),
                ('result_notification', models.CharField(default='Via SMS/Email', help_text='Result notification method', max_length=100)),
                ('eligibility_rules', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Students who have appeared for the examination</li><li>Application must be submitted within 15 days of result declaration</li><li>All dues must be cleared before applying</li><li>Valid student ID and hall ticket required</li></ul>', help_text='Eligibility rules')),
                ('required_documents', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Completed revaluation application form</li><li>Fee payment receipt</li><li>Student ID card copy</li><li>Hall ticket copy</li></ul>', help_text='Required documents')),
                ('controller_name', models.CharField(default='Dr. [Name]', help_text='Examination controller name', max_length=100)),
                ('controller_phone', models.CharField(default='+91-XXX-XXXX-XXX', help_text='Controller phone number', max_length=20)),
                ('controller_email', models.EmailField(default='exam@college.edu', help_text='Controller email', max_length=254)),
                ('controller_office_hours', models.CharField(default='9:00 AM - 5:00 PM', help_text='Controller office hours', max_length=100)),
                ('office_location', models.CharField(default='Ground Floor, Main Building', help_text='Examination office location', max_length=200)),
                ('office_phone', models.CharField(default='+91-XXX-XXXX-XXX', help_text='Office phone number', max_length=20)),
                ('office_email', models.EmailField(default='examoffice@college.edu', help_text='Office email', max_length=254)),
                ('office_working_days', models.CharField(default='Monday to Friday', help_text='Office working days', max_length=100)),
                ('application_form_file', models.FileField(blank=True, help_text='Revaluation application form PDF', null=True, upload_to='revaluation/forms/')),
                ('guidelines_file', models.FileField(blank=True, help_text='Revaluation guidelines PDF', null=True, upload_to='revaluation/forms/')),
                ('fee_structure_file', models.FileField(blank=True, help_text='Fee structure PDF', null=True, upload_to='revaluation/forms/')),
                ('important_notice', models.TextField(default='Revaluation results are final and binding. Students are advised to carefully consider before applying for revaluation. The college reserves the right to reject applications that do not meet the eligibility criteria or are submitted after the deadline.', help_text='Important notice text')),
                ('is_active', models.BooleanField(default=True, help_text='Make this revaluation information visible')),
            ],
            options={
                'verbose_name': 'Revaluation Information',
                'verbose_name_plural': 'Revaluation Information',
            },
        ),
    ]
