# Generated by Django 5.0.7 on 2025-09-05 08:56

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0029_revaluationinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExamRulesInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Examination Rules & Regulations', help_text='Page title', max_length=200)),
                ('subtitle', models.CharField(default='Important guidelines and rules for all examinations', help_text='Page subtitle', max_length=300)),
                ('timing_rules', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Students must arrive 15 minutes before exam time</li><li>Late entry is not permitted after 30 minutes</li><li>Hall ticket and ID card are mandatory</li><li>No student can leave within first 30 minutes</li></ul>', help_text='Timing and attendance rules')),
                ('prohibited_items', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Mobile phones and electronic devices</li><li>Calculators (unless specified)</li><li>Study materials and notes</li><li>Food and beverages</li></ul>', help_text='List of prohibited items')),
                ('conduct_rules', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Complete silence must be maintained throughout the examination</li><li>No talking or communication with other students</li><li>Any form of cheating will result in immediate disqualification</li><li>For any queries, students must raise their hand</li></ul>', help_text='Examination conduct rules')),
                ('answer_sheet_details', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Write roll number clearly on answer sheet</li><li>Use only blue or black ink pen</li><li>Do not write in margins or outside boxes</li><li>Number answers correctly</li></ul>', help_text='Answer sheet guidelines')),
                ('submission_rules', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Submit answer sheet 5 minutes before time</li><li>Raise hand when ready to submit</li><li>No additional sheets after submission</li><li>Leave immediately after submission</li></ul>', help_text='Submission rules')),
                ('violations_penalties', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li><strong>Cheating:</strong> Immediate disqualification</li><li><strong>Mobile Phone:</strong> Confiscation and penalty</li><li><strong>Late Entry:</strong> No entry after 30 minutes</li><li><strong>Misbehavior:</strong> Disciplinary action</li></ul>', help_text='Violations and penalties')),
                ('appeal_process', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Submit written appeal within 7 days</li><li>Contact examination controller</li><li>Appeal hearing within 15 days</li><li>Final decision by principal</li></ul>', help_text='Appeal process')),
                ('calculator_rules', models.TextField(default='Only non-programmable calculators are allowed for specific subjects. Check with invigilator before use.', help_text='Calculator usage rules')),
                ('open_book_rules', models.TextField(default='For open book examinations, only specified materials are allowed. No additional notes or materials.', help_text='Open book exam rules')),
                ('time_extension_rules', models.TextField(default='No time extensions are granted except in case of technical issues or emergencies with proper documentation.', help_text='Time extension rules')),
                ('controller_name', models.CharField(default='Dr. [Name]', help_text='Examination controller name', max_length=100)),
                ('controller_phone', models.CharField(default='+91-XXX-XXXX-XXX', help_text='Controller phone number', max_length=20)),
                ('controller_email', models.EmailField(default='exam@college.edu', help_text='Controller email', max_length=254)),
                ('controller_office_hours', models.CharField(default='9:00 AM - 5:00 PM', help_text='Controller office hours', max_length=100)),
                ('office_location', models.CharField(default='Ground Floor, Main Building', help_text='Examination office location', max_length=200)),
                ('office_phone', models.CharField(default='+91-XXX-XXXX-XXX', help_text='Office phone number', max_length=20)),
                ('office_email', models.EmailField(default='examoffice@college.edu', help_text='Office email', max_length=254)),
                ('office_working_days', models.CharField(default='Monday to Friday', help_text='Office working days', max_length=100)),
                ('important_notice', models.TextField(default='All students are required to strictly follow these examination rules and regulations. Violation of any rule will result in appropriate disciplinary action as per college policy. For any clarifications, contact the examination office well in advance.', help_text='Important notice text')),
                ('is_active', models.BooleanField(default=True, help_text='Make this exam rules information visible')),
            ],
            options={
                'verbose_name': 'Exam Rules Information',
                'verbose_name_plural': 'Exam Rules Information',
            },
        ),
    ]
