# Generated by Django 5.0.7 on 2025-09-05 09:21

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0030_examrulesinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchCenterInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Research Centers', help_text='Page title', max_length=200)),
                ('subtitle', models.CharField(default='Advancing knowledge through cutting-edge research and innovation', help_text='Page subtitle', max_length=300)),
                ('center1_name', models.CharField(default='Center for Advanced Sciences', help_text='First research center name', max_length=200)),
                ('center1_description', models.TextField(default='Dedicated to fundamental research in physics, chemistry, and mathematics with state-of-the-art laboratories and equipment.', help_text='First center description')),
                ('center1_areas', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Quantum Physics Research</li><li>Materials Science</li><li>Computational Chemistry</li></ul>', help_text='First center research areas')),
                ('center2_name', models.CharField(default='Computer Science Research Lab', help_text='Second research center name', max_length=200)),
                ('center2_description', models.TextField(default='Focusing on artificial intelligence, machine learning, and software engineering with cutting-edge computing resources.', help_text='Second center description')),
                ('center2_areas', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>AI & Machine Learning</li><li>Data Science</li><li>Cybersecurity</li></ul>', help_text='Second center research areas')),
                ('center3_name', models.CharField(default='Environmental Research Center', help_text='Third research center name', max_length=200)),
                ('center3_description', models.TextField(default='Committed to environmental sustainability and climate change research with modern analytical facilities.', help_text='Third center description')),
                ('center3_areas', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Climate Change Studies</li><li>Biodiversity Research</li><li>Renewable Energy</li></ul>', help_text='Third center research areas')),
                ('lab_infrastructure', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Advanced Analytical Instruments</li><li>High-Performance Computing Cluster</li><li>Clean Room Facilities</li><li>Specialized Research Equipment</li></ul>', help_text='Laboratory infrastructure details')),
                ('research_support', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Expert Faculty Mentorship</li><li>Research Grant Assistance</li><li>Publication Support</li><li>Conference Presentation Funding</li></ul>', help_text='Research support services')),
                ('physics_description', models.TextField(default='Quantum mechanics, solid state physics, and theoretical physics research.', help_text='Physics research area description')),
                ('biology_description', models.TextField(default='Molecular biology, genetics, and biotechnology research.', help_text='Biology research area description')),
                ('mathematics_description', models.TextField(default='Applied mathematics, statistics, and mathematical modeling.', help_text='Mathematics research area description')),
                ('social_sciences_description', models.TextField(default='Sociology, psychology, and interdisciplinary social research.', help_text='Social sciences research area description')),
                ('publications_count', models.PositiveIntegerField(default=150, help_text='Number of research papers published')),
                ('patents_count', models.PositiveIntegerField(default=25, help_text='Number of patents filed')),
                ('conferences_count', models.PositiveIntegerField(default=50, help_text='Number of conference presentations')),
                ('book_chapters_count', models.PositiveIntegerField(default=10, help_text='Number of book chapters')),
                ('grants_amount', models.DecimalField(decimal_places=2, default=25000000.0, help_text='Total research grants in INR', max_digits=10)),
                ('industry_collaborations', models.PositiveIntegerField(default=15, help_text='Number of industry collaborations')),
                ('international_partnerships', models.PositiveIntegerField(default=8, help_text='Number of international partnerships')),
                ('national_awards', models.PositiveIntegerField(default=5, help_text='Number of national awards')),
                ('student_opportunities', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Undergraduate Research Projects</li><li>Summer Research Internships</li><li>Thesis Research Support</li><li>Research Publication Opportunities</li></ul>', help_text='Research opportunities for students')),
                ('faculty_opportunities', django_ckeditor_5.fields.CKEditor5Field(default='<ul><li>Research Grant Applications</li><li>Collaborative Research Projects</li><li>International Exchange Programs</li><li>Research Equipment Access</li></ul>', help_text='Research opportunities for faculty')),
                ('director_name', models.CharField(default='Dr. [Research Director Name]', help_text='Research director name', max_length=100)),
                ('director_phone', models.CharField(default='+91-XXX-XXXX-XXX', help_text='Director phone number', max_length=20)),
                ('director_email', models.EmailField(default='research@college.edu', help_text='Director email', max_length=254)),
                ('director_office_hours', models.CharField(default='9:00 AM - 5:00 PM', help_text='Director office hours', max_length=100)),
                ('office_location', models.CharField(default='Research Block, 2nd Floor', help_text='Research office location', max_length=200)),
                ('office_phone', models.CharField(default='+91-XXX-XXXX-XXX', help_text='Office phone number', max_length=20)),
                ('office_email', models.EmailField(default='research.office@college.edu', help_text='Office email', max_length=254)),
                ('office_working_days', models.CharField(default='Monday to Friday', help_text='Office working days', max_length=100)),
                ('cta_title', models.CharField(default='Join Our Research Community', help_text='Call to action title', max_length=200)),
                ('cta_description', models.TextField(default='Interested in contributing to cutting-edge research? Contact our research office to learn about available opportunities for students and faculty members. Together, we can advance knowledge and make meaningful contributions to society.', help_text='Call to action description')),
                ('is_active', models.BooleanField(default=True, help_text='Make this research center information visible')),
            ],
            options={
                'verbose_name': 'Research Center Information',
                'verbose_name_plural': 'Research Center Information',
            },
        ),
    ]
