# Generated by Django 5.0.7 on 2025-09-05 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0031_researchcenterinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Publication title', max_length=500)),
                ('authors', models.CharField(help_text='Author names (comma separated)', max_length=1000)),
                ('abstract', models.TextField(help_text='Publication abstract')),
                ('journal_name', models.CharField(help_text='Journal or conference name', max_length=300)),
                ('journal_type', models.CharField(choices=[('international', 'International Journal'), ('national', 'National Journal'), ('conference', 'Conference Proceedings')], default='international', help_text='Type of publication', max_length=20)),
                ('department', models.CharField(choices=[('computer-science', 'Computer Science'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('commerce', 'Commerce'), ('management', 'Management')], help_text='Department', max_length=20)),
                ('publication_year', models.PositiveIntegerField(help_text='Year of publication')),
                ('citations', models.PositiveIntegerField(default=0, help_text='Number of citations')),
                ('impact_factor', models.DecimalField(blank=True, decimal_places=2, help_text='Journal impact factor', max_digits=4, null=True)),
                ('doi', models.CharField(blank=True, help_text='Digital Object Identifier', max_length=200)),
                ('url', models.URLField(blank=True, help_text='Publication URL')),
                ('pdf_file', models.FileField(blank=True, help_text='PDF file', upload_to='publications/')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this publication')),
                ('is_active', models.BooleanField(default=True, help_text='Make this publication visible')),
            ],
            options={
                'verbose_name': 'Publication',
                'verbose_name_plural': 'Publications',
                'ordering': ['-publication_year', '-citations'],
            },
        ),
        migrations.CreateModel(
            name='PublicationInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Research Publications', help_text='Page title', max_length=200)),
                ('subtitle', models.CharField(default='Explore our extensive collection of research publications, academic papers, and scholarly works that contribute to the advancement of knowledge across various disciplines.', help_text='Page subtitle', max_length=300)),
                ('total_publications', models.PositiveIntegerField(default=150, help_text='Total number of research papers')),
                ('book_chapters', models.PositiveIntegerField(default=25, help_text='Number of book chapters')),
                ('total_citations', models.PositiveIntegerField(default=500, help_text='Total number of citations')),
                ('awards_received', models.PositiveIntegerField(default=15, help_text='Number of awards received')),
                ('international_journals_count', models.PositiveIntegerField(default=85, help_text='Number of international journal papers')),
                ('international_citations', models.PositiveIntegerField(default=350, help_text='International journal citations')),
                ('national_journals_count', models.PositiveIntegerField(default=45, help_text='Number of national journal papers')),
                ('national_citations', models.PositiveIntegerField(default=120, help_text='National journal citations')),
                ('conference_papers_count', models.PositiveIntegerField(default=20, help_text='Number of conference papers')),
                ('conference_citations', models.PositiveIntegerField(default=30, help_text='Conference paper citations')),
                ('best_paper_awards', models.PositiveIntegerField(default=15, help_text='Number of best paper awards')),
                ('average_impact_factor', models.DecimalField(decimal_places=2, default=3.2, help_text='Average impact factor', max_digits=4)),
                ('international_collaborations', models.PositiveIntegerField(default=25, help_text='Number of international collaborations')),
                ('research_students', models.PositiveIntegerField(default=50, help_text='Number of research students')),
                ('cta_title', models.CharField(default='Interested in Collaborating?', help_text='Call to action title', max_length=200)),
                ('cta_description', models.TextField(default='Join our research community and contribute to cutting-edge research. We welcome collaborations with researchers, institutions, and industry partners worldwide.', help_text='Call to action description')),
                ('contact_email', models.EmailField(default='research@college.edu', help_text='Research contact email', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Make this publication information visible')),
            ],
            options={
                'verbose_name': 'Publication Information',
                'verbose_name_plural': 'Publication Information',
            },
        ),
    ]
