# Generated by Django 5.0.7 on 2025-09-05 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0032_publication_publicationinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryCollaboration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('company_name', models.CharField(help_text='Company name', max_length=200)),
                ('description', models.TextField(help_text='Collaboration description')),
                ('collaboration_type', models.CharField(help_text='Type of collaboration', max_length=100)),
                ('duration_years', models.PositiveIntegerField(help_text='Duration in years')),
                ('funding_amount', models.DecimalField(decimal_places=2, help_text='Funding amount in INR', max_digits=10)),
                ('contact_person', models.CharField(blank=True, help_text='Contact person', max_length=200)),
                ('company_website', models.URLField(blank=True, help_text='Company website')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this collaboration')),
                ('is_active', models.BooleanField(default=True, help_text='Make this collaboration visible')),
            ],
            options={
                'verbose_name': 'Industry Collaboration',
                'verbose_name_plural': 'Industry Collaborations',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Patent title', max_length=500)),
                ('inventors', models.CharField(help_text='Inventor names (comma separated)', max_length=1000)),
                ('description', models.TextField(help_text='Patent description')),
                ('patent_number', models.CharField(help_text='Patent number', max_length=100)),
                ('status', models.CharField(choices=[('granted', 'Granted'), ('pending', 'Pending'), ('filed', 'Filed'), ('published', 'Published')], default='pending', help_text='Patent status', max_length=20)),
                ('department', models.CharField(choices=[('computer-science', 'Computer Science'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('commerce', 'Commerce'), ('management', 'Management')], help_text='Department', max_length=20)),
                ('filing_year', models.PositiveIntegerField(help_text='Year of filing')),
                ('application_number', models.CharField(blank=True, help_text='Application number', max_length=100)),
                ('publication_date', models.DateField(blank=True, help_text='Publication date', null=True)),
                ('grant_date', models.DateField(blank=True, help_text='Grant date', null=True)),
                ('patent_url', models.URLField(blank=True, help_text='Patent URL')),
                ('pdf_file', models.FileField(blank=True, help_text='Patent PDF file', upload_to='patents/')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this patent')),
                ('is_active', models.BooleanField(default=True, help_text='Make this patent visible')),
            ],
            options={
                'verbose_name': 'Patent',
                'verbose_name_plural': 'Patents',
                'ordering': ['-filing_year', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PatentsProjectsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Patents & Projects', help_text='Page title', max_length=200)),
                ('subtitle', models.CharField(default='Explore our innovative research projects and intellectual property achievements that drive technological advancement and contribute to society.', help_text='Page subtitle', max_length=300)),
                ('total_patents', models.PositiveIntegerField(default=25, help_text='Total number of patents')),
                ('total_projects', models.PositiveIntegerField(default=50, help_text='Total number of research projects')),
                ('industry_collaborations', models.PositiveIntegerField(default=15, help_text='Number of industry collaborations')),
                ('research_funding', models.DecimalField(decimal_places=2, default=25000000.0, help_text='Total research funding in INR', max_digits=10)),
                ('innovation_awards', models.PositiveIntegerField(default=15, help_text='Number of innovation awards')),
                ('international_recognition', models.PositiveIntegerField(default=25, help_text='Number of countries with recognition')),
                ('active_partnerships', models.PositiveIntegerField(default=15, help_text='Number of active partnerships')),
                ('students_involved', models.PositiveIntegerField(default=100, help_text='Number of students involved')),
                ('cta_title', models.CharField(default='Interested in Collaborating?', help_text='Call to action title', max_length=200)),
                ('cta_description', models.TextField(default='Join our innovation ecosystem and contribute to cutting-edge research. We welcome collaborations with researchers, institutions, and industry partners worldwide.', help_text='Call to action description')),
                ('contact_email', models.EmailField(default='research@college.edu', help_text='Research contact email', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Make this patents & projects information visible')),
            ],
            options={
                'verbose_name': 'Patents & Projects Information',
                'verbose_name_plural': 'Patents & Projects Information',
            },
        ),
        migrations.CreateModel(
            name='ResearchProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Project title', max_length=500)),
                ('principal_investigator', models.CharField(help_text='Principal investigator name', max_length=200)),
                ('description', models.TextField(help_text='Project description')),
                ('department', models.CharField(choices=[('computer-science', 'Computer Science'), ('mathematics', 'Mathematics'), ('physics', 'Physics'), ('chemistry', 'Chemistry'), ('biology', 'Biology'), ('commerce', 'Commerce'), ('management', 'Management')], help_text='Department', max_length=20)),
                ('status', models.CharField(choices=[('ongoing', 'Ongoing'), ('completed', 'Completed'), ('planned', 'Planned'), ('suspended', 'Suspended')], default='ongoing', help_text='Project status', max_length=20)),
                ('start_year', models.PositiveIntegerField(help_text='Start year')),
                ('end_year', models.PositiveIntegerField(blank=True, help_text='End year', null=True)),
                ('funding_agency', models.CharField(help_text='Funding agency', max_length=200)),
                ('funding_amount', models.DecimalField(decimal_places=2, help_text='Funding amount in INR', max_digits=10)),
                ('project_duration', models.CharField(blank=True, help_text='Project duration', max_length=100)),
                ('team_members', models.TextField(blank=True, help_text='Team members')),
                ('project_url', models.URLField(blank=True, help_text='Project URL')),
                ('report_file', models.FileField(blank=True, help_text='Project report file', upload_to='projects/')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this project')),
                ('is_active', models.BooleanField(default=True, help_text='Make this project visible')),
            ],
            options={
                'verbose_name': 'Research Project',
                'verbose_name_plural': 'Research Projects',
                'ordering': ['-start_year', '-created_at'],
            },
        ),
    ]
