# Generated by Django 5.0.7 on 2025-09-05 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0033_industrycollaboration_patent_patentsprojectsinfo_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConsultancyExpertise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Expertise area title', max_length=100)),
                ('description', models.TextField(help_text='Expertise description')),
                ('icon_class', models.CharField(default='fas fa-cog', help_text='FontAwesome icon class', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Make this expertise visible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Consultancy Expertise',
                'verbose_name_plural': 'Consultancy Expertise Areas',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConsultancyInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Consultancy Services', help_text='Page title', max_length=200)),
                ('subtitle', models.CharField(default='Leveraging our academic expertise and research capabilities to provide innovative solutions for industry challenges. Our consultancy services bridge the gap between academia and industry.', help_text='Page subtitle', max_length=300)),
                ('total_projects', models.PositiveIntegerField(default=150, help_text='Total number of projects completed')),
                ('industry_partners', models.PositiveIntegerField(default=50, help_text='Number of industry partners')),
                ('revenue_generated', models.DecimalField(decimal_places=2, default=25000000.0, help_text='Total revenue generated in INR', max_digits=10)),
                ('client_satisfaction', models.PositiveIntegerField(default=95, help_text='Client satisfaction percentage')),
                ('cta_title', models.CharField(default='Ready to Transform Your Business?', help_text='Call to action title', max_length=200)),
                ('cta_description', models.TextField(default="Partner with us to leverage cutting-edge research and academic expertise for your business challenges. Let's work together to achieve your goals.", help_text='Call to action description')),
                ('contact_email', models.EmailField(default='consultancy@college.edu', help_text='Consultancy contact email', max_length=254)),
                ('is_active', models.BooleanField(default=True, help_text='Make this consultancy information visible')),
            ],
            options={
                'verbose_name': 'Consultancy Information',
                'verbose_name_plural': 'Consultancy Information',
            },
        ),
        migrations.CreateModel(
            name='ConsultancyService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Service title', max_length=200)),
                ('description', models.TextField(help_text='Service description')),
                ('service_type', models.CharField(choices=[('technology', 'Technology Consulting'), ('business', 'Business Analytics'), ('research', 'Research & Development'), ('training', 'Training & Development'), ('environmental', 'Environmental Consulting'), ('quality', 'Quality Assurance')], help_text='Type of service', max_length=20)),
                ('features', models.TextField(help_text='Service features (one per line)')),
                ('icon_class', models.CharField(default='fas fa-cog', help_text='FontAwesome icon class', max_length=50)),
                ('color_class', models.CharField(default='primary', help_text='Bootstrap color class', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this service')),
                ('is_active', models.BooleanField(default=True, help_text='Make this service visible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Consultancy Service',
                'verbose_name_plural': 'Consultancy Services',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='ConsultancySuccessStory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Success story title', max_length=200)),
                ('description', models.TextField(help_text='Success story description')),
                ('category', models.CharField(choices=[('technology', 'Technology'), ('research', 'Research'), ('training', 'Training'), ('business', 'Business'), ('environmental', 'Environmental')], help_text='Story category', max_length=20)),
                ('metric1_label', models.CharField(help_text='First metric label', max_length=50)),
                ('metric1_value', models.CharField(help_text='First metric value', max_length=20)),
                ('metric2_label', models.CharField(help_text='Second metric label', max_length=50)),
                ('metric2_value', models.CharField(help_text='Second metric value', max_length=20)),
                ('metric3_label', models.CharField(help_text='Third metric label', max_length=50)),
                ('metric3_value', models.CharField(help_text='Third metric value', max_length=20)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this success story')),
                ('is_active', models.BooleanField(default=True, help_text='Make this success story visible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Consultancy Success Story',
                'verbose_name_plural': 'Consultancy Success Stories',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
