# Generated by Django 5.0.7 on 2025-09-06 07:23

import django.db.models.deletion
import django.utils.timezone
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0035_student_studentdocument_studentloginlog_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSSNCCClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Club/Organization name', max_length=200)),
                ('club_type', models.CharField(choices=[('nss', 'NSS (National Service Scheme)'), ('ncc', 'NCC (National Cadet Corps)'), ('sports', 'Sports Club'), ('cultural', 'Cultural Club'), ('tech', 'Technology Club'), ('literary', 'Literary Club'), ('environmental', 'Environmental Club'), ('music', 'Music Club'), ('dance', 'Dance Club'), ('drama', 'Drama Club'), ('photography', 'Photography Club'), ('debate', 'Debate Club'), ('other', 'Other')], help_text='Type of club/organization', max_length=20)),
                ('description', django_ckeditor_5.fields.CKEditor5Field(help_text='Detailed description of the club')),
                ('short_description', models.TextField(help_text='Brief description for cards', max_length=500)),
                ('coordinator_name', models.CharField(help_text='Club coordinator name', max_length=100)),
                ('coordinator_email', models.EmailField(help_text='Coordinator email', max_length=254)),
                ('coordinator_phone', models.CharField(blank=True, help_text='Coordinator phone', max_length=15)),
                ('main_activities', django_ckeditor_5.fields.CKEditor5Field(help_text='Main activities and programs')),
                ('upcoming_events', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Upcoming events and activities')),
                ('logo', models.ImageField(blank=True, help_text='Club logo', null=True, upload_to='nss_ncc_clubs/logos/')),
                ('cover_image', models.ImageField(blank=True, help_text='Cover image', null=True, upload_to='nss_ncc_clubs/covers/')),
                ('is_active', models.BooleanField(default=True, help_text='Make this club visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this club prominently')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook page URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram page URL')),
                ('website_url', models.URLField(blank=True, help_text='Official website URL')),
            ],
            options={
                'verbose_name': 'NSS-NCC Club',
                'verbose_name_plural': 'NSS-NCC Clubs',
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='NSSNCCAchievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Achievement title', max_length=200)),
                ('description', models.TextField(help_text='Achievement description')),
                ('achievement_type', models.CharField(choices=[('award', 'Award'), ('recognition', 'Recognition'), ('certificate', 'Certificate'), ('trophy', 'Trophy'), ('medal', 'Medal'), ('other', 'Other')], default='award', help_text='Type of achievement', max_length=20)),
                ('achieved_by', models.CharField(help_text='Who achieved this (individual/team)', max_length=200)),
                ('achievement_date', models.DateField(help_text='Date of achievement')),
                ('organization', models.CharField(help_text='Organization that gave the achievement', max_length=200)),
                ('certificate_image', models.ImageField(blank=True, help_text='Certificate or award image', null=True, upload_to='nss_ncc_clubs/achievements/')),
                ('is_active', models.BooleanField(default=True, help_text='Make this achievement visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this achievement prominently')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('related_club', models.ForeignKey(help_text='Related club', on_delete=django.db.models.deletion.CASCADE, related_name='achievements', to='college_website.nssnccclub')),
            ],
            options={
                'verbose_name': 'NSS-NCC Achievement',
                'verbose_name_plural': 'NSS-NCC Achievements',
                'ordering': ['-achievement_date', 'display_order'],
            },
        ),
        migrations.CreateModel(
            name='NSSNCCGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Image title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Image description')),
                ('category', models.CharField(choices=[('events', 'Events'), ('activities', 'Activities'), ('camps', 'Camps'), ('competitions', 'Competitions'), ('meetings', 'Meetings'), ('achievements', 'Achievements'), ('general', 'General')], default='general', help_text='Image category', max_length=20)),
                ('image', models.ImageField(help_text='Gallery image', upload_to='nss_ncc_clubs/gallery/')),
                ('is_active', models.BooleanField(default=True, help_text='Make this image visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this image prominently')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('related_club', models.ForeignKey(help_text='Related club', on_delete=django.db.models.deletion.CASCADE, related_name='gallery_images', to='college_website.nssnccclub')),
            ],
            options={
                'verbose_name': 'NSS-NCC Gallery Image',
                'verbose_name_plural': 'NSS-NCC Gallery Images',
                'ordering': ['display_order', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NSSNCCNotice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Notice title', max_length=200)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(help_text='Notice content')),
                ('category', models.CharField(choices=[('general', 'General'), ('event', 'Event'), ('recruitment', 'Recruitment'), ('achievement', 'Achievement'), ('meeting', 'Meeting'), ('camp', 'Camp'), ('competition', 'Competition'), ('other', 'Other')], default='general', help_text='Notice category', max_length=20)),
                ('priority', models.CharField(choices=[('low', 'Low'), ('normal', 'Normal'), ('high', 'High'), ('urgent', 'Urgent')], default='normal', help_text='Notice priority', max_length=10)),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, help_text='When to publish this notice')),
                ('expiry_date', models.DateTimeField(blank=True, help_text='When this notice expires (optional)', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Make this notice visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this notice prominently')),
                ('attachment', models.FileField(blank=True, help_text='Notice attachment', null=True, upload_to='nss_ncc_clubs/notices/')),
                ('related_club', models.ForeignKey(help_text='Related club', on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='college_website.nssnccclub')),
            ],
            options={
                'verbose_name': 'NSS-NCC Notice',
                'verbose_name_plural': 'NSS-NCC Notices',
                'ordering': ['-publish_date', '-created_at'],
            },
        ),
    ]
