# Generated by Django 5.0.7 on 2025-09-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0036_nssnccclub_nssnccachievement_nssnccgallery_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='herobanner',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero image displayed on the right side (optional)', null=True, upload_to='hero_banner/'),
        ),
    ]
