# Generated by Django 5.0.7 on 2025-09-06 16:13

import colorfield.fields
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0036_nssnccclub_nssnccachievement_nssnccgallery_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeroCarouselSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_enabled', models.BooleanField(default=True, help_text='Enable hero carousel')),
                ('auto_play', models.BooleanField(default=True, help_text='Enable auto-play')),
                ('default_interval', models.PositiveIntegerField(default=5000, help_text='Default auto-play interval (ms)')),
                ('show_indicators', models.BooleanField(default=True, help_text='Show carousel indicators')),
                ('show_controls', models.BooleanField(default=True, help_text='Show navigation controls')),
                ('pause_on_hover', models.BooleanField(default=True, help_text='Pause carousel on hover')),
                ('enable_keyboard', models.BooleanField(default=True, help_text='Enable keyboard navigation')),
                ('enable_touch', models.BooleanField(default=True, help_text='Enable touch/swipe navigation')),
                ('transition_duration', models.PositiveIntegerField(default=600, help_text='Transition duration (ms)')),
                ('fade_effect', models.BooleanField(default=True, help_text='Enable fade transition effect')),
                ('mobile_height', models.CharField(default='24rem', help_text='Mobile carousel height', max_length=20)),
                ('tablet_height', models.CharField(default='28rem', help_text='Tablet carousel height', max_length=20)),
                ('desktop_height', models.CharField(default='24rem', help_text='Desktop carousel height', max_length=20)),
            ],
            options={
                'verbose_name': 'Hero Carousel Settings',
                'verbose_name_plural': 'Hero Carousel Settings',
            },
        ),
        migrations.CreateModel(
            name='HeroCarouselSlide',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Main heading of the slide', max_length=200)),
                ('subtitle', models.TextField(help_text='Subtitle/description text')),
                ('slide_type', models.CharField(choices=[('welcome', 'Welcome & Programs'), ('admissions', 'Admissions'), ('research', 'Research & Innovation'), ('student_life', 'Student Life'), ('custom', 'Custom')], default='welcome', max_length=20)),
                ('is_active', models.BooleanField(default=True, help_text='Whether this slide is active')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Order of display (0 = first)')),
                ('badge_text', models.CharField(blank=True, help_text="Badge text (e.g., 'Welcome to Excellence')", max_length=100)),
                ('badge_icon', models.CharField(default='fas fa-star', help_text='FontAwesome icon class for badge', max_length=50)),
                ('badge_color', colorfield.fields.ColorField(default='#FFD700', help_text='Badge background color', image_field=None, max_length=25, samples=None)),
                ('primary_button_text', models.CharField(blank=True, help_text='Primary button text', max_length=100)),
                ('primary_button_url', models.URLField(blank=True, help_text='Primary button URL')),
                ('primary_button_color', colorfield.fields.ColorField(default='#FFC107', help_text='Primary button color', image_field=None, max_length=25, samples=None)),
                ('primary_button_icon', models.CharField(default='fas fa-arrow-right', help_text='Primary button icon', max_length=50)),
                ('secondary_button_text', models.CharField(blank=True, help_text='Secondary button text', max_length=100)),
                ('secondary_button_url', models.URLField(blank=True, help_text='Secondary button URL')),
                ('secondary_button_color', colorfield.fields.ColorField(default='#FFFFFF', help_text='Secondary button color', image_field=None, max_length=25, samples=None)),
                ('secondary_button_icon', models.CharField(default='fas fa-info-circle', help_text='Secondary button icon', max_length=50)),
                ('gradient_type', models.CharField(choices=[('blue-purple', 'Blue to Purple'), ('green-teal', 'Green to Teal'), ('purple-pink', 'Purple to Pink'), ('orange-red', 'Orange to Red'), ('custom', 'Custom Gradient')], default='blue-purple', max_length=20)),
                ('custom_gradient_from', colorfield.fields.ColorField(default='#1e3a8a', help_text='Custom gradient start color', image_field=None, max_length=25, samples=None)),
                ('custom_gradient_to', colorfield.fields.ColorField(default='#7c3aed', help_text='Custom gradient end color', image_field=None, max_length=25, samples=None)),
                ('custom_gradient_via', colorfield.fields.ColorField(blank=True, default='#6b21a8', help_text='Custom gradient middle color (optional)', image_field=None, max_length=25, samples=None)),
                ('show_statistics', models.BooleanField(default=True, help_text='Show statistics cards')),
                ('stat_1_number', models.CharField(default='18+', help_text='First statistic number', max_length=20)),
                ('stat_1_label', models.CharField(default='Courses', help_text='First statistic label', max_length=50)),
                ('stat_1_icon', models.CharField(default='fas fa-graduation-cap', help_text='First statistic icon', max_length=50)),
                ('stat_1_color', colorfield.fields.ColorField(default='#3B82F6', help_text='First statistic card color', image_field=None, max_length=25, samples=None)),
                ('stat_2_number', models.CharField(default='5000+', help_text='Second statistic number', max_length=20)),
                ('stat_2_label', models.CharField(default='Students', help_text='Second statistic label', max_length=50)),
                ('stat_2_icon', models.CharField(default='fas fa-users', help_text='Second statistic icon', max_length=50)),
                ('stat_2_color', colorfield.fields.ColorField(default='#8B5CF6', help_text='Second statistic card color', image_field=None, max_length=25, samples=None)),
                ('stat_3_number', models.CharField(default='150+', help_text='Third statistic number', max_length=20)),
                ('stat_3_label', models.CharField(default='Faculty', help_text='Third statistic label', max_length=50)),
                ('stat_3_icon', models.CharField(default='fas fa-chalkboard-teacher', help_text='Third statistic icon', max_length=50)),
                ('stat_3_color', colorfield.fields.ColorField(default='#10B981', help_text='Third statistic card color', image_field=None, max_length=25, samples=None)),
                ('stat_4_number', models.CharField(default='25+', help_text='Fourth statistic number', max_length=20)),
                ('stat_4_label', models.CharField(default='Years', help_text='Fourth statistic label', max_length=50)),
                ('stat_4_icon', models.CharField(default='fas fa-award', help_text='Fourth statistic icon', max_length=50)),
                ('stat_4_color', colorfield.fields.ColorField(default='#F59E0B', help_text='Fourth statistic card color', image_field=None, max_length=25, samples=None)),
                ('show_content_cards', models.BooleanField(default=False, help_text='Show content cards (for admissions, research, etc.)')),
                ('content_title', models.CharField(blank=True, help_text='Content section title', max_length=200)),
                ('content_icon', models.CharField(default='fas fa-university', help_text='Content section icon', max_length=50)),
                ('content_items', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Content items (HTML format)')),
                ('auto_play_interval', models.PositiveIntegerField(default=5000, help_text='Auto-play interval in milliseconds')),
                ('show_indicators', models.BooleanField(default=True, help_text='Show carousel indicators')),
                ('show_controls', models.BooleanField(default=True, help_text='Show navigation controls')),
            ],
            options={
                'verbose_name': 'Hero Carousel Slide',
                'verbose_name_plural': 'Hero Carousel Slides',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
