# Generated by Django 5.0.7 on 2025-09-06 17:51

import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0037_herocarouselsettings_herocarouselslide'),
    ]

    operations = [
        migrations.AddField(
            model_name='program',
            name='additional_benefits',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Additional benefits and facilities'),
        ),
        migrations.AddField(
            model_name='program',
            name='assessment_methods',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Assessment and evaluation methods'),
        ),
        migrations.AddField(
            model_name='program',
            name='class_timings',
            field=models.CharField(blank=True, help_text='Class timings (e.g., 9:00 AM - 1:15 PM)', max_length=200),
        ),
        migrations.AddField(
            model_name='program',
            name='co_po_mapping',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='CO-PO mapping and alignment details'),
        ),
        migrations.AddField(
            model_name='program',
            name='course_outcomes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Course Outcomes (COs) - specific learning objectives'),
        ),
        migrations.AddField(
            model_name='program',
            name='elective_options',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Available elective subjects and options'),
        ),
        migrations.AddField(
            model_name='program',
            name='entrepreneurship',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Entrepreneurship and startup opportunities'),
        ),
        migrations.AddField(
            model_name='program',
            name='expert_faculty',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Information about expert faculty and their qualifications'),
        ),
        migrations.AddField(
            model_name='program',
            name='first_year_subjects',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='First year subjects and curriculum'),
        ),
        migrations.AddField(
            model_name='program',
            name='further_studies',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Higher education and further study options'),
        ),
        migrations.AddField(
            model_name='program',
            name='global_opportunities',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='International and global opportunities'),
        ),
        migrations.AddField(
            model_name='program',
            name='government_careers',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Government services and civil service opportunities'),
        ),
        migrations.AddField(
            model_name='program',
            name='industry_connect',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Industry connections and partnerships'),
        ),
        migrations.AddField(
            model_name='program',
            name='infrastructure',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Modern infrastructure and facilities'),
        ),
        migrations.AddField(
            model_name='program',
            name='media_journalism_careers',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Media and journalism career paths'),
        ),
        migrations.AddField(
            model_name='program',
            name='private_sector_careers',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Private sector career opportunities'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_outcomes',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Program Outcomes (POs) - what students will achieve'),
        ),
        migrations.AddField(
            model_name='program',
            name='research_opportunities',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Research opportunities and projects'),
        ),
        migrations.AddField(
            model_name='program',
            name='second_year_subjects',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Second year subjects and curriculum'),
        ),
        migrations.AddField(
            model_name='program',
            name='teaching_careers',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Teaching and education career opportunities'),
        ),
        migrations.AddField(
            model_name='program',
            name='third_year_subjects',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Third year subjects and curriculum (if applicable)'),
        ),
        migrations.AddField(
            model_name='program',
            name='timetable_info',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Academic timetable and schedule information'),
        ),
        migrations.AddField(
            model_name='program',
            name='weekly_schedule',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Weekly class schedule and subject distribution'),
        ),
    ]
