# Generated by Django 5.0.7 on 2025-09-08 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0037_add_hero_image_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collegeinfo',
            name='courses_count',
            field=models.CharField(default='25+', max_length=10),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='faculty_staff_count',
            field=models.CharField(default='150+', max_length=10),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='students_count',
            field=models.CharField(default='12,500+', max_length=10),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='years_of_excellence',
            field=models.CharField(default='30+', max_length=10),
        ),
    ]
