# Generated by Django 5.0.7 on 2025-09-07 01:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0038_add_program_enhanced_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='facebook_url',
            field=models.URLField(blank=True, help_text='Facebook profile URL'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='google_scholar_url',
            field=models.URLField(blank=True, help_text='Google Scholar profile URL'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='Instagram profile URL'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='LinkedIn profile URL'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='orcid_id',
            field=models.CharField(blank=True, help_text='ORCID ID', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='researchgate_url',
            field=models.URLField(blank=True, help_text='ResearchGate profile URL'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='scopus_id',
            field=models.CharField(blank=True, help_text='Scopus Author ID', max_length=50),
        ),
        migrations.AddField(
            model_name='faculty',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='Twitter profile URL'),
        ),
        migrations.AddField(
            model_name='faculty',
            name='website_url',
            field=models.URLField(blank=True, help_text='Personal website URL'),
        ),
    ]
