# Generated by Django 5.0.7 on 2025-09-09 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0038_alter_collegeinfo_courses_count_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Facility title', max_length=200)),
                ('description', models.TextField(help_text='Facility description')),
                ('facility_type', models.CharField(choices=[('classroom', 'Smart Classrooms'), ('laboratory', 'Modern Laboratories'), ('library', 'Digital Library'), ('computer_lab', 'Computer Laboratories'), ('research_lab', 'Research Laboratories'), ('seminar_hall', 'Seminar Halls'), ('auditorium', 'Auditorium'), ('other', 'Other')], default='other', help_text='Type of facility', max_length=50)),
                ('icon_class', models.CharField(default='fas fa-building', help_text='Font Awesome icon class', max_length=100)),
                ('color_class', models.CharField(default='blue', help_text='Color theme', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Facility image', null=True, upload_to='infrastructure/facilities/')),
                ('features', models.TextField(blank=True, help_text='Features list (one per line)')),
                ('is_active', models.BooleanField(default=True, help_text='Make this facility visible')),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this facility prominently')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Academic Facility',
                'verbose_name_plural': 'Academic Facilities',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='InfrastructureInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(default='Infrastructure & Facilities', help_text='Page title', max_length=200)),
                ('subtitle', models.CharField(default='State-of-the-art infrastructure designed to provide students with the best learning environment and modern amenities for academic excellence.', help_text='Page subtitle', max_length=300)),
                ('hero_title', models.CharField(default='Infrastructure & Facilities', help_text='Hero section title', max_length=200)),
                ('hero_subtitle', models.CharField(default='State-of-the-art infrastructure designed to provide students with the best learning environment and modern amenities for academic excellence.', help_text='Hero section subtitle', max_length=500)),
                ('hero_image', models.ImageField(blank=True, help_text='Hero section background image', null=True, upload_to='infrastructure/hero/')),
                ('hero_badge_text', models.CharField(default='Modern Facilities', help_text='Hero section badge text', max_length=100)),
                ('overview_title', models.CharField(default='Our Infrastructure at a Glance', help_text='Overview section title', max_length=200)),
                ('overview_description', models.TextField(default='We provide world-class infrastructure that supports academic excellence and student development through modern facilities and technology.', help_text='Overview section description')),
                ('cta_title', models.CharField(default='Experience Our World-Class Infrastructure', help_text='Call to action title', max_length=200)),
                ('cta_description', models.TextField(default='Visit our campus to see our modern facilities and infrastructure that support academic excellence and student success.', help_text='Call to action description')),
                ('cta_button_text', models.CharField(default='Schedule a Visit', help_text='Call to action button text', max_length=100)),
                ('cta_button_url', models.CharField(default='/contact/', help_text='Call to action button URL', max_length=200)),
                ('is_active', models.BooleanField(default=True, help_text='Make this infrastructure information visible')),
            ],
            options={
                'verbose_name': 'Infrastructure Information',
                'verbose_name_plural': 'Infrastructure Information',
            },
        ),
        migrations.CreateModel(
            name='InfrastructureStatistic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text="Statistic title (e.g., 'Classrooms')", max_length=100)),
                ('value', models.CharField(help_text="Statistic value (e.g., '25+', '100%')", max_length=50)),
                ('description', models.CharField(blank=True, help_text='Optional description', max_length=200)),
                ('icon_class', models.CharField(default='fas fa-building', help_text='Font Awesome icon class', max_length=100)),
                ('statistic_type', models.CharField(choices=[('classrooms', 'Classrooms'), ('laboratories', 'Laboratories'), ('library_books', 'Library Books'), ('wifi_coverage', 'WiFi Coverage'), ('campus_area', 'Campus Area'), ('computer_labs', 'Computer Labs'), ('sports_facilities', 'Sports Facilities'), ('other', 'Other')], default='other', help_text='Type of statistic', max_length=50)),
                ('color_class', models.CharField(default='blue', help_text='Color theme (blue, emerald, purple, orange)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Make this statistic visible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Infrastructure Statistic',
                'verbose_name_plural': 'Infrastructure Statistics',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='SportsFacility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Sports facility title', max_length=200)),
                ('description', models.TextField(help_text='Sports facility description')),
                ('sports_type', models.CharField(choices=[('outdoor', 'Outdoor Sports'), ('indoor', 'Indoor Sports'), ('gymnasium', 'Gymnasium'), ('swimming', 'Swimming Pool'), ('other', 'Other')], default='other', help_text='Type of sports facility', max_length=50)),
                ('icon_class', models.CharField(default='fas fa-futbol', help_text='Font Awesome icon class', max_length=100)),
                ('color_class', models.CharField(default='green', help_text='Color theme', max_length=50)),
                ('image', models.ImageField(blank=True, help_text='Sports facility image', null=True, upload_to='infrastructure/sports/')),
                ('is_active', models.BooleanField(default=True, help_text='Make this sports facility visible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Sports Facility',
                'verbose_name_plural': 'Sports Facilities',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='StudentAmenity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Amenity title', max_length=200)),
                ('description', models.TextField(help_text='Amenity description')),
                ('amenity_type', models.CharField(choices=[('cafeteria', 'Cafeteria'), ('transport', 'Transport'), ('parking', 'Parking'), ('medical', 'Medical Center'), ('hostel', 'Hostel'), ('banking', 'Banking'), ('atm', 'ATM'), ('bookstore', 'Bookstore'), ('other', 'Other')], default='other', help_text='Type of amenity', max_length=50)),
                ('icon_class', models.CharField(default='fas fa-utensils', help_text='Font Awesome icon class', max_length=100)),
                ('color_class', models.CharField(default='pink', help_text='Color theme', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Make this amenity visible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Student Amenity',
                'verbose_name_plural': 'Student Amenities',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.CreateModel(
            name='TechnologyInfrastructure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Technology infrastructure title', max_length=200)),
                ('description', models.TextField(help_text='Technology infrastructure description')),
                ('tech_type', models.CharField(choices=[('internet', 'High-Speed Internet'), ('it_infrastructure', 'IT Infrastructure'), ('video_conferencing', 'Video Conferencing'), ('security', 'Security Systems'), ('network', 'Network Infrastructure'), ('software', 'Software Systems'), ('other', 'Other')], default='other', help_text='Type of technology', max_length=50)),
                ('icon_class', models.CharField(default='fas fa-wifi', help_text='Font Awesome icon class', max_length=100)),
                ('color_class', models.CharField(default='indigo', help_text='Color theme', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Make this technology infrastructure visible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
            ],
            options={
                'verbose_name': 'Technology Infrastructure',
                'verbose_name_plural': 'Technology Infrastructure',
                'ordering': ['display_order', 'title'],
            },
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='courses_count',
            field=models.CharField(default='18+', max_length=10),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='faculty_staff_count',
            field=models.CharField(default='50+', max_length=10),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='students_count',
            field=models.CharField(default='8000+', max_length=10),
        ),
        migrations.AlterField(
            model_name='collegeinfo',
            name='years_of_excellence',
            field=models.CharField(default='25+', max_length=10),
        ),
    ]
