# Generated by Django 5.0.7 on 2025-09-09 06:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0039_infrastructure_models'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfrastructurePhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Photo title/caption', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Photo description')),
                ('image', models.ImageField(help_text='Infrastructure photo', upload_to='infrastructure/photos/')),
                ('section_type', models.CharField(choices=[('academic', 'Academic Facilities'), ('sports', 'Sports Facilities'), ('technology', 'Technology Infrastructure'), ('amenities', 'Student Amenities'), ('general', 'General Infrastructure')], default='general', help_text='Section type', max_length=50)),
                ('is_featured', models.BooleanField(default=False, help_text='Feature this photo prominently')),
                ('is_active', models.BooleanField(default=True, help_text='Make this photo visible')),
                ('display_order', models.PositiveIntegerField(default=0, help_text='Display order (lower numbers first)')),
                ('academic_facility', models.ForeignKey(blank=True, help_text='Associated academic facility', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='college_website.academicfacility')),
                ('sports_facility', models.ForeignKey(blank=True, help_text='Associated sports facility', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='college_website.sportsfacility')),
                ('student_amenity', models.ForeignKey(blank=True, help_text='Associated student amenity', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='college_website.studentamenity')),
                ('technology_infrastructure', models.ForeignKey(blank=True, help_text='Associated technology infrastructure', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='college_website.technologyinfrastructure')),
            ],
            options={
                'verbose_name': 'Infrastructure Photo',
                'verbose_name_plural': 'Infrastructure Photos',
                'ordering': ['display_order', 'title'],
            },
        ),
    ]
