# Generated by Django 5.0.7 on 2025-09-07 02:56

import django.db.models.deletion
import django_ckeditor_5.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0039_add_social_media_fields_to_faculty'),
    ]

    operations = [
        migrations.CreateModel(
            name='NonAcademicStaff',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(help_text='Full name of staff member', max_length=200)),
                ('slug', models.SlugField(help_text='URL-friendly version of name', unique=True)),
                ('designation', models.CharField(choices=[('registrar', 'Registrar'), ('deputy_registrar', 'Deputy Registrar'), ('assistant_registrar', 'Assistant Registrar'), ('accountant', 'Accountant'), ('librarian', 'Librarian'), ('assistant_librarian', 'Assistant Librarian'), ('lab_technician', 'Lab Technician'), ('computer_operator', 'Computer Operator'), ('clerk', 'Clerk'), ('peon', 'Peon'), ('security_guard', 'Security Guard'), ('cleaner', 'Cleaner'), ('driver', 'Driver'), ('cook', 'Cook'), ('other', 'Other')], max_length=30)),
                ('designation_order', models.PositiveIntegerField(default=0, help_text='Order for display (lower first)')),
                ('employee_id', models.CharField(blank=True, help_text='Employee ID', max_length=50)),
                ('highest_qualification', models.CharField(choices=[('phd', 'Ph.D'), ('mphil', 'M.Phil'), ('masters', 'Masters'), ('bachelors', 'Bachelors'), ('diploma', 'Diploma'), ('certificate', 'Certificate'), ('other', 'Other')], default='bachelors', max_length=20)),
                ('qualifications', models.TextField(help_text='Detailed qualifications')),
                ('specialization', models.CharField(blank=True, help_text='Area of specialization', max_length=200)),
                ('experience_years', models.PositiveIntegerField(default=0, help_text='Years of experience')),
                ('joining_date', models.DateField(blank=True, help_text='Date of joining institution', null=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('office_location', models.CharField(blank=True, max_length=200)),
                ('linkedin_url', models.URLField(blank=True, help_text='LinkedIn profile URL')),
                ('google_scholar_url', models.URLField(blank=True, help_text='Google Scholar profile URL')),
                ('researchgate_url', models.URLField(blank=True, help_text='ResearchGate profile URL')),
                ('orcid_id', models.CharField(blank=True, help_text='ORCID ID', max_length=50)),
                ('scopus_id', models.CharField(blank=True, help_text='Scopus Author ID', max_length=50)),
                ('twitter_url', models.URLField(blank=True, help_text='Twitter profile URL')),
                ('facebook_url', models.URLField(blank=True, help_text='Facebook profile URL')),
                ('instagram_url', models.URLField(blank=True, help_text='Instagram profile URL')),
                ('website_url', models.URLField(blank=True, help_text='Personal website URL')),
                ('job_description', models.TextField(blank=True, help_text='Job responsibilities and duties')),
                ('skills', models.TextField(blank=True, help_text='Skills and competencies, one per line')),
                ('photo', models.ImageField(blank=True, help_text='Staff photo', null=True, upload_to='staff/')),
                ('cv_file', models.FileField(blank=True, help_text='CV/Resume PDF', null=True, upload_to='staff/cv/')),
                ('bio', django_ckeditor_5.fields.CKEditor5Field(blank=True, help_text='Staff biography')),
                ('message', models.TextField(blank=True, help_text='Message to students/colleagues')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False, help_text='Show in featured staff')),
                ('show_on_website', models.BooleanField(default=True, help_text='Display on public website')),
                ('meta_title', models.CharField(blank=True, help_text='SEO title', max_length=200)),
                ('meta_description', models.TextField(blank=True, help_text='SEO description', max_length=300)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='non_academic_staff', to='college_website.department')),
            ],
            options={
                'verbose_name': 'Non-Academic Staff Member',
                'verbose_name_plural': 'Non-Academic Staff Members',
                'ordering': ['department', 'designation_order', 'name'],
                'unique_together': {('department', 'slug')},
            },
        ),
    ]
