# Generated by Django 5.0.7 on 2025-09-07 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0040_add_non_academic_staff_model'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbarinfo',
            name='border_radius',
            field=models.DecimalField(decimal_places=1, default=0.0, help_text='Navbar border radius in pixels', max_digits=3),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='box_shadow',
            field=models.CharField(default='0 1px 3px -1px rgba(0, 0, 0, 0.1), 0 1px 2px -1px rgba(0, 0, 0, 0.06)', help_text='Box shadow CSS value', max_length=100),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='brand_font_size',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='Brand font size in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='dropdown_item_font_size',
            field=models.DecimalField(decimal_places=2, default=0.75, help_text='Dropdown item font size in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='dropdown_item_margin',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='Dropdown item margin in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='dropdown_item_padding_horizontal',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Dropdown item horizontal padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='dropdown_item_padding_vertical',
            field=models.DecimalField(decimal_places=2, default=0.3, help_text='Dropdown item vertical padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='dropdown_padding',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Dropdown padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='hover_scale',
            field=models.DecimalField(decimal_places=2, default=1.05, help_text='Hover scale effect', max_digits=3),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='logo_height',
            field=models.PositiveIntegerField(default=28, help_text='Logo height in pixels'),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='mega_menu_columns',
            field=models.PositiveIntegerField(default=4, help_text='Number of columns in mega menu'),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='mega_menu_padding',
            field=models.DecimalField(decimal_places=2, default=0.8, help_text='Mega menu padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='mega_menu_width',
            field=models.CharField(default='auto', help_text='Mega menu width (auto, 100%, or specific value)', max_length=20),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='menu_font_size',
            field=models.DecimalField(decimal_places=2, default=0.65, help_text='Menu font size in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='menu_item_border_radius',
            field=models.DecimalField(decimal_places=1, default=2.0, help_text='Menu item border radius in pixels', max_digits=3),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='menu_item_gap',
            field=models.DecimalField(decimal_places=3, default=0.005, help_text='Gap between menu items in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='menu_item_margin',
            field=models.DecimalField(decimal_places=3, default=0.005, help_text='Menu item margin in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='menu_item_padding_horizontal',
            field=models.DecimalField(decimal_places=2, default=0.2, help_text='Menu item horizontal padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='menu_item_padding_vertical',
            field=models.DecimalField(decimal_places=2, default=0.15, help_text='Menu item vertical padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='menu_line_height',
            field=models.DecimalField(decimal_places=1, default=1.1, help_text='Menu line height', max_digits=3),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='mobile_brand_font_size',
            field=models.DecimalField(decimal_places=2, default=0.7, help_text='Mobile brand font size in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='mobile_breakpoint',
            field=models.PositiveIntegerField(default=992, help_text='Mobile breakpoint in pixels'),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='mobile_logo_height',
            field=models.PositiveIntegerField(default=20, help_text='Mobile logo height in pixels'),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='mobile_menu_font_size',
            field=models.DecimalField(decimal_places=2, default=0.65, help_text='Mobile menu font size in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='mobile_navbar_height',
            field=models.PositiveIntegerField(default=35, help_text='Mobile navbar height in pixels'),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='mobile_padding_horizontal',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Mobile horizontal padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='navbar_height',
            field=models.PositiveIntegerField(default=40, help_text='Navbar height in pixels'),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='navbar_padding_bottom',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Bottom padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='navbar_padding_horizontal',
            field=models.DecimalField(decimal_places=2, default=0.5, help_text='Horizontal padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='navbar_padding_top',
            field=models.DecimalField(decimal_places=2, default=0.1, help_text='Top padding in rem', max_digits=4),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='tablet_breakpoint',
            field=models.PositiveIntegerField(default=768, help_text='Tablet breakpoint in pixels'),
        ),
        migrations.AddField(
            model_name='navbarinfo',
            name='transition_duration',
            field=models.DecimalField(decimal_places=1, default=0.3, help_text='Transition duration in seconds', max_digits=3),
        ),
    ]
