# Generated by Django 5.0.7 on 2025-09-11 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0040_infrastructure_photos'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicCalendar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('academic_year', models.CharField(choices=[('2024-25', '2024-25'), ('2023-24', '2023-24'), ('2022-23', '2022-23'), ('2021-22', '2021-22')], help_text='Academic year (e.g., 2024-25)', max_length=7, unique=True)),
                ('title', models.CharField(default='Academic Calendar', help_text='Calendar title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description of the academic year')),
                ('start_date', models.DateField(help_text='Academic year start date')),
                ('end_date', models.DateField(help_text='Academic year end date')),
                ('is_active', models.BooleanField(default=False, help_text='Mark as current active academic year')),
                ('is_published', models.BooleanField(default=True, help_text='Make calendar publicly visible')),
            ],
            options={
                'verbose_name': 'Academic Calendar',
                'verbose_name_plural': 'Academic Calendars',
                'ordering': ['-academic_year'],
            },
        ),
        migrations.CreateModel(
            name='AcademicEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(help_text='Event title', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Event description')),
                ('event_type', models.CharField(choices=[('academic', 'Academic'), ('exam', 'Examination'), ('holiday', 'Holiday'), ('break', 'Break'), ('event', 'Event'), ('orientation', 'Orientation'), ('result', 'Result')], default='academic', help_text='Type of event', max_length=20)),
                ('semester', models.CharField(choices=[('first', 'First Semester'), ('second', 'Second Semester'), ('both', 'Both Semesters')], default='both', help_text='Associated semester', max_length=10)),
                ('start_date', models.DateField(help_text='Event start date')),
                ('end_date', models.DateField(blank=True, help_text='Event end date (optional)', null=True)),
                ('is_important', models.BooleanField(default=False, help_text='Mark as important event')),
                ('is_published', models.BooleanField(default=True, help_text='Make event publicly visible')),
                ('ordering', models.PositiveIntegerField(default=0, help_text='Display order')),
                ('calendar', models.ForeignKey(help_text='Associated academic calendar', on_delete=django.db.models.deletion.CASCADE, related_name='events', to='college_website.academiccalendar')),
            ],
            options={
                'verbose_name': 'Academic Event',
                'verbose_name_plural': 'Academic Events',
                'ordering': ['start_date', 'ordering'],
            },
        ),
    ]
