# Generated by Django 5.0.7 on 2025-09-11 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('college_website', '0041_academiccalendar_academicevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='academiccalendar',
            name='download_count',
            field=models.PositiveIntegerField(default=0, help_text='Number of times PDF has been downloaded'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='pdf_file',
            field=models.FileField(blank=True, help_text='Upload PDF version of the academic calendar', null=True, upload_to='academic_calendars/pdfs/'),
        ),
        migrations.AddField(
            model_name='academiccalendar',
            name='pdf_file_size',
            field=models.CharField(blank=True, help_text='PDF file size (auto-calculated)', max_length=20),
        ),
    ]
